# Generated by Django 4.0.5 on 2023-01-20 08:21

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('network', '0003_alter_abstractnewtext_postdate'),
    ]

    operations = [
        migrations.AlterField(
            model_name='abstractnewtext',
            name='postDate',
            field=models.DateTimeField(default=datetime.datetime(2023, 1, 20, 9, 21, 13, 176197)),
        ),
    ]
