# Generated by Django 4.0.5 on 2022-07-16 20:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auctions', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='bid',
            name='bidPrice',
            field=models.FloatField(null=True),
        ),
        migrations.AddField(
            model_name='comment',
            name='comment',
            field=models.CharField(max_length=4096, null=True),
        ),
        migrations.AddField(
            model_name='listings',
            name='askingPrice',
            field=models.FloatField(null=True),
        ),
        migrations.AddField(
            model_name='listings',
            name='category',
            field=models.CharField(max_length=64, null=True),
        ),
        migrations.AddField(
            model_name='listings',
            name='description',
            field=models.CharField(max_length=4096, null=True),
        ),
        migrations.AddField(
            model_name='listings',
            name='imageUrl',
            field=models.CharField(max_length=4096, null=True),
        ),
        migrations.AddField(
            model_name='listings',
            name='title',
            field=models.CharField(max_length=64, null=True),
        ),
    ]
