# Generated by Django 4.0.5 on 2022-07-23 20:10

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('auctions', '0003_remove_listings_bid_bid_biddatetime_bid_listing'),
    ]

    operations = [
        migrations.RenameField(
            model_name='listings',
            old_name='askingPrice',
            new_name='currentPrice',
        ),
        migrations.RemoveField(
            model_name='comment',
            name='userCommented',
        ),
        migrations.AddField(
            model_name='comment',
            name='auction',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='auctions.listings'),
        ),
        migrations.AlterField(
            model_name='comment',
            name='commentator',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.DeleteModel(
            name='Commentator',
        ),
    ]
