# Generated by Django 4.0.5 on 2022-07-23 19:49

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('auctions', '0002_bid_bidprice_comment_comment_listings_askingprice_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='listings',
            name='bid',
        ),
        migrations.AddField(
            model_name='bid',
            name='bidDateTime',
            field=models.DateTimeField(null=True),
        ),
        migrations.AddField(
            model_name='bid',
            name='listing',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='auctions.listings'),
        ),
    ]
