(function(g){var window=this;'use strict';var uZa=function(a,b){var c=[];return g.Wr(a,{query:b},function(d){c.push(d.getValue());return d.continue()}).then(function(){return c})},H3=function(a,b){return"getAll"in IDBIndex.prototype?g.Fr(a.j.getAll(b,void 0)):uZa(a,b)},vZa=function(a,b){return g.Lr(a,["captions"],{mode:"readonly",
dc:!0},function(c){return g.Eoa(c.objectStore("captions"),b)})},wZa=function(a){var b=new g.Dw("und",new g.dz("Default","und",!0));
b.captionTracks=a.captionTracks;return b},xZa=function(a){return new g.Pg(function(b,c){var d=a.length,e=[];
if(d)for(var f=function(n,p){d--;e[n]=p;0==d&&b(e)},h=function(n){c(n)},l=0,m;l<a.length;l++)m=a[l],g.rda(m,g.Ta(f,l),h);
else b(e)})},I3=function(a){this.j=a},J3=function(){I3.apply(this,arguments)},K3=function(){J3.apply(this,arguments)},L3=function(){J3.apply(this,arguments)},M3=function(){J3.apply(this,arguments)},N3=function(){I3.apply(this,arguments)},O3=function(){J3.apply(this,arguments)},P3=function(){J3.apply(this,arguments)},Q3=function(){J3.apply(this,arguments)},R3=function(){J3.apply(this,arguments)},S3=function(){J3.apply(this,arguments)},T3=function(){J3.apply(this,arguments)},U3=function(){J3.apply(this,
arguments)},V3=function(){I3.apply(this,arguments)},W3=function(){J3.apply(this,arguments)},X3=function(){J3.apply(this,arguments)},Y3=function(){J3.apply(this,arguments)},Z3=function(){J3.apply(this,arguments)},$3=function(){J3.apply(this,arguments)},a4=function(){J3.apply(this,arguments)},b4=function(){J3.apply(this,arguments)},c4=function(){I3.apply(this,arguments)},d4=function(){J3.apply(this,arguments)},e4=function(){J3.apply(this,arguments)},f4=function(){J3.apply(this,arguments)},g4=function(){J3.apply(this,
arguments)},h4=function(){J3.apply(this,arguments)},i4=function(){J3.apply(this,arguments)},j4=function(){J3.apply(this,arguments)},k4=function(){J3.apply(this,arguments)},l4=function(){J3.apply(this,arguments)},m4=function(){J3.apply(this,arguments)},n4=function(){J3.apply(this,arguments)},o4=function(){J3.apply(this,arguments)},p4=function(){J3.apply(this,arguments)},q4=function(){J3.apply(this,arguments)},r4=function(){J3.apply(this,arguments)},s4=function(){J3.apply(this,arguments)},t4=function(){J3.apply(this,
arguments)},u4=function(){J3.apply(this,arguments)},v4=function(){J3.apply(this,arguments)},w4=function(){J3.apply(this,arguments)},x4=function(){J3.apply(this,arguments)},y4=function(){J3.apply(this,arguments)},z4=function(){J3.apply(this,arguments)},A4=function(){J3.apply(this,arguments)},B4=function(){J3.apply(this,arguments)},C4=function(){J3.apply(this,arguments)},D4=function(){J3.apply(this,arguments)},E4=function(){J3.apply(this,arguments)},F4=function(){J3.apply(this,arguments)},G4=function(){J3.apply(this,
arguments)},H4=function(){J3.apply(this,arguments)},I4=function(){J3.apply(this,arguments)},J4=function(a){a=a.key||a.id;
if(!a)throw Error("Entity key is missing");return a},yZa=function(){if(K4)return K4();
var a={};K4=g.us("PersistentEntityStoreDb",{Ur:(a.EntityStore={Ko:1},a.EntityAssociationStore={Ko:2},a),shared:!1,upgrade:function(b,c){c(1)&&g.Or(g.Jr(b,"EntityStore",{keyPath:"key"}),"entityType","entityType");c(2)&&(b=g.Jr(b,"EntityAssociationStore",{keyPath:["parentEntityKey","childEntityKey"]}),g.Or(b,"byParentEntityKey","parentEntityKey"),g.Or(b,"byChildEntityKey","childEntityKey"))},
version:3});return K4()},zZa=function(a){return g.Zr(yZa(),a)},L4=function(a,b){b=void 0===b?{}:b;
g.rr.call(this,g.kVa[a],Object.assign({},{name:"PESEncoderError",type:a},b));this.type=a;this.level="WARNING";Object.setPrototypeOf(this,L4.prototype)},AZa=function(a){return new L4("WRONG_DATA_TYPE",{dW:a})},BZa=function(a){return a instanceof Error?new L4("UNKNOWN_ENCODE_ERROR",{originalMessage:a.message}):new L4("UNKNOWN_ENCODE_ERROR")},CZa=function(a){return a instanceof Error?new L4("UNKNOWN_DECODE_ERROR",{originalMessage:a.message}):new L4("UNKNOWN_DECODE_ERROR")},DZa=function(a,b){a=a instanceof
L4?a:b(a);
g.S(a);throw a;},EZa=function(){},FZa=function(a,b,c){try{return a.B(b,c)}catch(d){DZa(d,BZa)}},M4=function(a){a=(new TextEncoder).encode(a).subarray(0,16);
var b=new Uint8Array(16);b.set(a);return b},N4=function(a){this.j=a},HZa=function(a){var b=GZa[a];
if(b)return b;g.wu(new g.rr("Entity model not found.",{entityType:a}))},IZa=function(a,b){this.j=a;
this.u=b;this.B={}},P4=function(a,b){a:{a=O4(a.u,b.version);
try{var c=a.u(b.data,b.key);break a}catch(d){DZa(d,CZa)}c=void 0}return c},Q4=function(a,b,c){return a.j.objectStore("EntityStore").get(b).then(function(d){if(d){if(c&&d.entityType!==c)throw Error("Incorrect entity type");
return P4(a,d)}})},R4=function(a,b,c){return c?(c=c.map(function(d){return Q4(a,d,b)}),g.Dr.all(c)):H3(a.j.objectStore("EntityStore").index("entityType"),IDBKeyRange.only(b)).then(function(d){return d.map(function(e){return P4(a,e)})})},T4=function(a,b,c){var d=J4(b),e=O4(a.u,1),f=Object.assign({},b);
return a.j.objectStore("EntityStore").get(d).then(function(h){if(h){if(h.entityType!==c)throw Error("Incorrect entity type");f.entityMetadata||(h=P4(a,h),f.entityMetadata=h.entityMetadata)}}).then(function(){var h={key:d,
entityType:c,data:FZa(e,f,d),version:1};return g.Dr.all([g.Mr(a.j.objectStore("EntityStore"),h),JZa(a,f,c)])}).then(function(){S4(a,d,c);
return d})},U4=function(a,b,c){b=b.map(function(d){return T4(a,d,c)});
return g.Dr.all(b)},V4=function(a,b,c){if(null==c?0:c.Ut){var d=new Set;
return KZa(a,b,d).then(function(){for(var f=[],h=g.r(d),l=h.next();!l.done;l=h.next())f.push(V4(a,l.value));return g.Dr.all(f).then(function(){})})}var e=g.vC(b).entityType;
return g.Dr.all([a.j.objectStore("EntityStore").delete(b),W4(a,b)]).then(function(){S4(a,b,e)})},LZa=function(a,b){return g.Wr(a.j.objectStore("EntityStore").index("entityType"),{query:IDBKeyRange.only(b)},function(c){return g.Dr.all([c.delete(),
W4(a,c.zB())]).then(function(){S4(a,c.zB(),b);return c.continue()})})},S4=function(a,b,c){var d=a.B[c];
d||(d=new Set,a.B[c]=d);d.add(b)},MZa=function(a,b,c){var d=J4(b);
c=HZa(c);if(!c)return g.Dr.resolve([]);c=new c(b);a=a.j.objectStore("EntityAssociationStore");b=[];c=g.r(c.u());for(var e=c.next();!e.done;e=c.next())b.push(g.Mr(a,{parentEntityKey:d,childEntityKey:e.value}));return g.Dr.all(b).then(function(f){return f.map(function(h){return h[1]})})},W4=function(a,b){return a.j.objectStore("EntityAssociationStore").index("byParentEntityKey").delete(IDBKeyRange.only(b))},JZa=function(a,b,c){var d=J4(b);
return W4(a,d).then(function(){return MZa(a,b,c)})},KZa=function(a,b,c){if(c.has(b))return g.Dr.resolve(void 0);
c.add(b);return NZa(a,b).then(function(d){return a.j.objectStore("EntityAssociationStore").index("byParentEntityKey").delete(IDBKeyRange.only(b)).then(function(){return d})}).then(function(d){var e=g.Dr.resolve(void 0),f={};
d=g.r(d);for(var h=d.next();!h.done;f={ND:f.ND},h=d.next())f.ND=h.value,e=e.then(function(l){return function(){return KZa(a,l.ND,c)}}(f));
return e}).then(function(){})},NZa=function(a,b){var c=a.j.objectStore("EntityAssociationStore");
return H3(c.index("byParentEntityKey"),IDBKeyRange.only(b)).then(function(d){var e=[];d=g.r(d);for(var f=d.next();!f.done;f=d.next())f=f.value,e.push(H3(c.index("byChildEntityKey"),f.childEntityKey));return g.Dr.all(e)}).then(function(d){var e=[];
d=g.r(d);for(var f=d.next();!f.done;f=d.next())f=f.value,1===f.length&&e.push(f[0].childEntityKey);return e})},X4=function(){},OZa=function(){this.j={};
this.j[0]=new X4;if(!g.Q("aes_pes_encoder_killswitch")){var a=this.j;try{var b=g.sr();var c=M4(b);var d=new N4(new g.tA(c),new g.sA(c))}catch(e){throw a=e instanceof Error?new L4("KEY_CREATION_FAILED",{originalMessage:e.message}):new L4("KEY_CREATION_FAILED"),g.S(a),a;}a[1]=d}},O4=function(a,b){b=void 0===b?0:b;
a=a.j[b];if(!a)throw b=new L4("INVALID_ENCODER_VERSION",{dW:b}),g.S(b),b;return a},Y4=function(a,b){g.I.call(this);
this.token=a;this.j=b;this.observers=[];a=new g.C.BroadcastChannel("PERSISTENT_ENTITY_STORE_SYNC:"+g.sr());a.onmessage=this.u.bind(this);this.channel=a},Z4=function(a,b,c){var d,e,f,h;
return g.B(function(l){if(1==l.j)return g.A(l,zZa(a.token),2);if(3!=l.j)return d=l.u,g.A(l,g.Lr(d,["EntityStore","EntityAssociationStore"],b,function(m){e=new IZa(m,a.j);return c(e)}),3);
f=l.u;e&&(h=e.B,0<Object.keys(h).length&&(a.channel.postMessage(h),PZa(a,h)));return l.return(f)})},$4=function(a,b){a.observers.push(b);
return function(){var c=a.observers.indexOf(b);0<=c&&a.observers.splice(c,1)}},a5=function(a,b,c){return Z4(a,{mode:"readwrite",
dc:!0},function(d){return T4(d,b,c)})},QZa=function(a,b){return Z4(a,{mode:"readwrite",
dc:!0},function(c){return U4(c,b,"offlineOrchestrationActionWrapperEntity")})},RZa=function(a,b){return Z4(a,{mode:"readwrite",
dc:!0},function(c){return V4(c,b)})},b5=function(a,b,c){return Z4(a,{mode:"readonly",
dc:!0},function(d){return Q4(d,b,c)})},c5=function(a,b,c){return Z4(a,{mode:"readonly",
dc:!0},function(d){return R4(d,b,c)})},PZa=function(a,b){a=g.r(a.observers);
for(var c=a.next();!c.done;c=a.next())c=c.value,c(b)},SZa=function(){var a,b,c;
return g.B(function(d){if(1==d.j)return g.wa(d,2),g.A(d,g.fs(),4);if(2!=d.j){a=d.u;if(!a||!g.tr()||"undefined"===typeof g.C.BroadcastChannel)return d.return();b=new OZa;return d.return(new Y4(a,b))}c=g.za(d);c instanceof Error&&g.S(c);return d.return()})},e5=function(){d5||(d5=SZa());
return d5},TZa=function(a){var b;
a=null==(b=a.options)?void 0:b.persistenceOption;return"ENTITY_PERSISTENCE_OPTION_PERSIST"===a||"ENTITY_PERSISTENCE_OPTION_INMEMORY_AND_PERSIST"===a},UZa=function(a){var b;
return g.B(function(c){return 1==c.j?g.A(c,e5(),2):(b=c.u)?g.A(c,Z4(b,"readwrite",function(d){for(var e={},f={},h=g.r(a),l=h.next();!l.done;f={gh:f.gh,gt:f.gt},l=h.next())f.gh=l.value,f.gh.entityKey&&TZa(f.gh)&&(f.gt=g.Fe(f.gh.payload),l=void 0,"ENTITY_MUTATION_TYPE_REPLACE"===f.gh.type&&(l=function(m){return function(){return T4(d,m.gh.payload[m.gt],m.gt)}}(f)),"ENTITY_MUTATION_TYPE_DELETE"===f.gh.type&&(l=function(m){return function(){return V4(d,m.gh.entityKey)}}(f)),"ENTITY_MUTATION_TYPE_UPDATE"===
f.gh.type&&(l=function(m){return function(){return d.updateEntity(m.gh.entityKey,m.gh.payload[m.gt],m.gt)}}(f)),l&&(e[f.gh.entityKey]=e[f.gh.entityKey]?e[f.gh.entityKey].then(l):l()));
return g.Dr.all(Object.values(e))}),0):c.return()})},VZa=function(a){var b;
return g.B(function(c){if(1==c.j){b=a.mutations;if(!b||0>=b.length)return c.return();if(g.lD){var d={type:"ENTITY_LOADED"};void 0!==b&&(d.payload=b);g.lD.dispatch(d)}return g.A(c,UZa(b),2)}b.length=0;g.va(c)})},WZa=function(a){return void 0!==a},XZa=function(a){var b=g.GC();
b=Object.assign({},b);a=Object.assign({},a);for(var c in b)a[c]?(4!==b[c]&&(b[c]=a[c]),delete a[c]):2!==b[c]&&(b[c]=4);Object.assign(b,a);g.Owa(b);JSON.stringify(b);return b},YZa=function(a){var b,c;
return g.B(function(d){if(1==d.j)return g.A(d,g.fs(),2);if(3!=d.j)return(b=d.u)?g.A(d,g.JC(b),3):d.return();c=d.u;return d.return(g.Lr(c,["index","media","captions"],{mode:"readwrite",dc:!0},function(e){var f=IDBKeyRange.bound(a+"|",a+"~");e=[e.objectStore("index").delete(f),e.objectStore("media").delete(f),e.objectStore("captions").delete(f)];return g.Dr.all(e).then(function(){})}))})},ZZa=function(){var a,b;
return g.B(function(c){if(1==c.j)return g.A(c,g.fs(),2);if(3!=c.j){a=c.u;if(!a)throw g.Br("rvdfd");return g.A(c,g.JC(a),3)}b=c.u;return c.return(g.Lr(b,["index","media"],{mode:"readwrite",dc:!0},function(d){var e={};return g.Ur(d.objectStore("index"),{},function(f){var h=f.getKey().match(/^([\w\-_]+)\|(a|v)$/),l=g.Dr.resolve(void 0);if(h){var m=h[1];h=h[2];e[m]=e[m]||{};var n;e[m][h]=g.Twa(null==(n=f.getValue())?void 0:n.fmts)}else l=f.delete().then(function(){});
return g.Dr.all([f.continue(),l]).then(function(p){return g.r(p).next().value})}).then(function(){for(var f={},h=g.r(Object.keys(e)),l=h.next();!l.done;l=h.next()){l=l.value;
var m=e[l].v;f[l]=e[l].a&&m?1:2}var n=XZa(f);return g.Hoa(d.objectStore("media"),{},function(p){var q=p.getKey().match(g.Xwa);q&&f[q[1]]||d.objectStore("media").delete(p.getKey());return p.continue()}).then(function(){return n})})}))})},$Za=function(a,b){var c,d;
return g.B(function(e){if(1==e.j)return g.A(e,g.fs(),2);if(3!=e.j){c=e.u;if(!c)throw g.Br("wct");return g.A(e,g.JC(c),3)}d=e.u;return g.A(e,g.Lr(d,["captions"],{mode:"readwrite",dc:!0},function(f){var h=[];f=f.objectStore("captions");for(var l=0;l<b.length;l++){var m=g.Mr(f,b[l],a+"|"+b[l].metadata.vss_id);h.push(m)}return g.Dr.all(h)}),0)})},a_a=function(a){var b,c,d;
return g.B(function(e){if(1==e.j)return b=IDBKeyRange.bound(a+"|",a+"~"),g.A(e,g.fs(),2);if(3!=e.j){c=e.u;if(!c)throw g.Br("gactfv");return g.A(e,g.JC(c),3)}d=e.u;return e.return(vZa(d,b))})},b_a=function(a){return g.B(function(b){g.IC(a,0);
return b.return(YZa(a))})},c_a=function(a){return{context:g.KF(),
videoIds:a}},d_a=function(a){return{context:g.KF(),
playlistIds:a}},f5=function(a,b,c){g.wu(new g.rr("Woffle: "+a,c?{cotn:c}:""));
b instanceof Error&&g.wu(b)},e_a=function(a){var b,c,d,e,f,h,l,m,n,p,q,t,u,x,y,z,D;
return g.B(function(H){if(1==H.j)return g.A(H,Z4(a,{mode:"readonly",dc:!0},function(G){return R4(G,"playbackData").then(function(L){var aa=L.map(function(sa){return sa.transfer}).filter(function(sa){return!!sa}),M=L.map(function(sa){return sa.offlineVideoPolicy}).filter(function(sa){return!!sa});
aa=R4(G,"transfer",aa);M=R4(G,"offlineVideoPolicy",M);return g.Dr.all([aa,M]).then(function(sa){var xa=g.r(sa);sa=xa.next().value;xa=xa.next().value;return[L,sa,xa]})})}),2);
b=H.u;c=g.r(b);d=c.next().value;e=c.next().value;f=c.next().value;h=d;l=e;m=f;n={};p={};q=g.r(l);for(t=q.next();!t.done;t=q.next())(u=t.value)&&(n[u.key]=u);x=g.r(m);for(y=x.next();!y.done;y=x.next())(z=y.value)&&(p[z.key]=z);D=h.map(function(G){var L=n[G.transfer],aa=p[G.offlineVideoPolicy];G=g.vC(aa.key).entityId;if("OFFLINE_VIDEO_POLICY_ACTION_DISABLE"===aa.action){var M="OFFLINE_VIDEO_STATE_DISABLED";aa.expirationTimestamp&&Number(aa.expirationTimestamp)<Date.now()/1E3&&(M="OFFLINE_VIDEO_STATE_EXPIRED");
aa=M}else if("OFFLINE_VIDEO_POLICY_ACTION_DOWNLOAD_FAILED"===aa.action)aa="OFFLINE_VIDEO_STATE_OFFLINE_FAILED";else{switch(null==L?void 0:L.transferState){case "TRANSFER_STATE_TRANSFER_IN_QUEUE":M="OFFLINE_VIDEO_STATE_PENDING";break;case "TRANSFER_STATE_TRANSFERRING":M="OFFLINE_VIDEO_STATE_TRANSFERRING";break;case "TRANSFER_STATE_PAUSED_BY_USER":M="OFFLINE_VIDEO_STATE_PAUSED_TRANSFER";break;case "TRANSFER_STATE_FAILED":M="OFFLINE_VIDEO_STATE_OFFLINE_FAILED";break;case "TRANSFER_STATE_COMPLETE":M=
"OFFLINE_VIDEO_STATE_PLAYABLE";break;case "TRANSFER_STATE_WAITING_FOR_PLAYER_RESPONSE_REFRESH":M="OFFLINE_VIDEO_STATE_STREAMS_OUT_OF_DATE";break;default:M="OFFLINE_VIDEO_STATE_UNKNOWN"}if("OFFLINE_VIDEO_STATE_OFFLINE_FAILED"===M)switch(null==L?void 0:L.failureReason){case "TRANSFER_FAILURE_REASON_EXTERNAL_FILESYSTEM_WRITE":case "TRANSFER_FAILURE_REASON_FILESYSTEM_WRITE":M="OFFLINE_VIDEO_STATE_OUT_OF_STORAGE_ERROR";break;case "TRANSFER_FAILURE_REASON_STREAM_MISSING":M="OFFLINE_VIDEO_STATE_STREAMS_MISSING";
break;case "TRANSFER_FAILURE_REASON_NETWORK":case "TRANSFER_FAILURE_REASON_NETWORK_LOST":M="OFFLINE_VIDEO_STATE_NETWORK_ERROR"}aa=M}G={id:G,videoState:aa};if(null==L?0:L.cotn)G.cotn=L.cotn;if(null==L?0:L.maximumDownloadQuality)G.selectedVideoQuality=null==L?void 0:L.maximumDownloadQuality;return G});
return H.return({offlineVideos:D})})},f_a=function(a){var b;
return g.B(function(c){if(1==c.j)return g.A(c,e_a(a),2);b=c.u;g.mr("offlineStateSnapshot",b);g.va(c)})},g5=function(a){g.I.call(this);
this.api=a;"undefined"!==typeof g.C.BroadcastChannel&&(this.j=new g.C.BroadcastChannel("PLAYER_OFFLINE_ERROR_SYNC:"+g.sr()),this.j.onmessage=this.B.bind(this),this.u=new g.C.BroadcastChannel("PLAYER_OFFLINE_PAUSE_SYNC:"+g.sr()),this.u.onmessage=this.C.bind(this))},h5=function(a,b){a.api.Ia("onOfflineOperationFailure",b);
var c;null==(c=a.j)||c.postMessage(b)},g_a=function(){this.locks=navigator.locks},h_a=function(){try{var a=g.La("ytglobal.locks_");
if(a)return a;var b;if(b=navigator){var c=navigator;b="locks"in c&&!!c.locks}if(b)return g.C.localStorage&&g.C.localStorage.getItem("noop"),a=new g_a,g.Ka("ytglobal.locks_",a),a}catch(d){}},j_a=function(a,b,c,d){var e=this;
this.P=a;this.U=b;this.visibility=c;this.K=d;this.C=this.I=this.D=this.u=this.j=!1;this.J=new g.K(function(){i_a(e)});
this.visibility.subscribe("visibilitystatechange",function(){e.nf()})},k_a=function(a){if(!a.u&&!a.j){var b=h_a();
if(b){a.u=!0;var c=g.sr("OfflineLockManager");b.request("woffle_orchestration_leader:"+c,{},function(){var d,e,f,h;return g.B(function(l){switch(l.j){case 1:return g.wa(l,2),a.B=new g.ji,a.j=!0,a.u=!1,g.A(l,a.P(),4);case 4:return g.A(l,a.B.promise,5);case 5:g.ya(l,0);break;case 2:d=g.za(l),(null==(f=(e=a).K)?0:f.call(e,"wo_relinquish_leadership_on_lock_request_error"))||i_a(a),d instanceof Error&&(h=d,h.args=[{name:"WoLockManagerError",BC:d.name}],g.S(h)),g.va(l)}})})}}},l_a=function(a){a.j&&(a.C=
!0,i5(a))},m_a=function(a,b){a.j&&(a.D=b,i5(a))},n_a=function(a,b){a.j&&(a.I=b,i5(a))},i5=function(a){a.I&&a.D&&a.C&&a.visibility.isBackground()?g.zn(a.J,6E4):a.J.stop()},i_a=function(a){a.B&&a.B.resolve();
a.j=!1;a.u=!1;a.U()},j5=function(a,b){var c=b.nj;
a.encryptedVideoId=b.videoId;a.cotn=c.cotn;a.offlineabilityFormatType=c.maximumDownloadQuality;var d;a.isRefresh=null!=(d=c.isRefresh)?d:!1;var e;a.softErrorCount=null!=(e=c.transferRetryCount)?e:0;g.mr("offlineTransferStatusChanged",a)},o_a=function(a,b,c,d){b=Math.floor(b/1024).toFixed();
j5({transferStatusType:"TRANSFER_STATUS_TYPE_PROCESSING",statusType:"OFFLINING_STARTED",transferFirstStarted:!!d,alreadyDownloadedKbytes:b,totalFetchedKbytes:b,totalContentKbytes:Math.floor(c/1024).toFixed()},a)},p_a=function(a){j5({transferStatusType:"TRANSFER_STATUS_TYPE_DEQUEUED_BY_USER_PAUSE",
statusType:"SUSPENDED"},a)},q_a=function(a){switch(a){case "TRANSFER_FAILURE_REASON_FILESYSTEM_WRITE":case "TRANSFER_FAILURE_REASON_EXTERNAL_FILESYSTEM_WRITE":return"OFFLINE_DATABASE_ERROR";
case "TRANSFER_FAILURE_REASON_PLAYABILITY":return"NOT_PLAYABLE";case "TRANSFER_FAILURE_REASON_TOO_MANY_RETRIES":return"TOO_MANY_RETRIES";case "TRANSFER_FAILURE_REASON_INTERNAL":return"OFFLINE_DOWNLOAD_CONTROLLER_ERROR";case "TRANSFER_FAILURE_REASON_STREAM_MISSING":return"STREAM_VERIFICATION_FAILED";case "TRANSFER_FAILURE_REASON_SERVER":case "TRANSFER_FAILURE_REASON_SERVER_PROPERTY_MISSING":return"OFFLINE_REQUEST_FAILURE";case "TRANSFER_FAILURE_REASON_NETWORK":return"OFFLINE_NETWORK_ERROR";default:return"UNKNOWN_FAILURE_REASON"}},
k5=function(){},l5=function(){},m5=function(a){if(a.includes(":"))throw Error("Invalid user cache name: "+a);
return a+":"+g.sr("CacheStorage get")},r_a=function(){return g.B(function(a){if(void 0!==n5)return a.return(n5);
n5=new Promise(function(b){var c;return g.B(function(d){switch(d.j){case 1:return g.wa(d,2),g.A(d,o5.open("test-only"),4);case 4:return g.A(d,o5.delete("test-only"),5);case 5:g.ya(d,3);break;case 2:if(c=g.za(d),c instanceof Error&&"SecurityError"===c.name)return b(!1),d.return();case 3:b("caches"in window),g.va(d)}})});
return a.return(n5)})},q5=function(){return g.B(function(a){if(1==a.j)return g.A(a,r_a(),2);
if(!a.u)return a.return(void 0);p5||(p5=new l5);return a.return(p5)})},s_a=function(){var a;
return g.B(function(b){return 1==b.j?g.A(b,q5(),2):(a=b.u)?b.return(a.delete("yt-player-local-img")):b.return(!0)})},r5=function(a){var b,c;
return g.B(function(d){if(1==d.j)return g.A(d,q5(),2);if(3!=d.j){b=d.u;if(!b)throw Error("Cache API not supported");return a.length?g.A(d,b.open("yt-player-local-img"),3):d.return()}c=d.u;return g.A(d,Promise.all(a.map(function(e){return c.delete(e)})),0)})},s5=function(a){var b,c;
return g.B(function(d){if(1==d.j)return g.A(d,q5(),2);if(3!=d.j){b=d.u;if(!b)throw Error("Cache API not supported");return a.length?g.A(d,b.open("yt-player-local-img"),3):d.return()}c=d.u;return g.A(d,c.addAll(a),0)})},t5=function(a){var b,c,d;
return 0<(null!=(d=null==(b=a.actionMetadata)?void 0:null==(c=b.retryScheduleIntervalsInSeconds)?void 0:c.length)?d:0)},u5=function(a){return"OFFLINE_ORCHESTRATION_ACTION_TYPE_ADD"===a.actionType&&!!a.entityKey},v5=function(a){return"OFFLINE_ORCHESTRATION_ACTION_TYPE_REFRESH"===a.actionType&&!!a.entityKey},w5=function(a){return"OFFLINE_ORCHESTRATION_ACTION_TYPE_DELETE"===a.actionType&&!!a.entityKey},A5=function(a,b,c,d){var e,f,h,l,m,n,p,q,t,u,x,y,z,D,H,G,L,aa,M,sa,xa,ba,pa,Ya,Ua,nb,ob,fc;
return g.B(function(cb){switch(cb.j){case 1:return e=g.wC(a,"ytMainVideoEntity"),f=g.wC(a,"mainVideoEntity"),h=g.wC(a,"ytMainChannelEntity"),l=g.wC(a,"transfer"),g.A(cb,Z4(b,{mode:"readonly",dc:!0},function(Db){return g.Dr.all([Q4(Db,e,"ytMainVideoEntity"),Q4(Db,f,"mainVideoEntity"),Q4(Db,h,"ytMainChannelEntity"),Q4(Db,l,"transfer"),R4(Db,"ytMainChannelEntity"),R4(Db,"offlineOrchestrationActionWrapperEntity")])}),2);
case 2:m=cb.u;n=g.r(m);p=n.next().value;q=n.next().value;t=n.next().value;u=n.next().value;x=n.next().value;y=n.next().value;z=p;D=q;H=t;G=u;L=x;aa=y;if(!(z||D||H)){cb.Oa(3);break}M=z?x5(z.thumbnail):D?x5(D.thumbnail):[];if(!H){sa=[];cb.Oa(4);break}return g.A(cb,t_a(H,L),5);case 5:sa=cb.u;case 4:return xa=sa,g.A(cb,r5(M.concat(xa)),3);case 3:ba=[];pa=g.wC(a,"ytMainDownloadedVideoEntity");Ya=g.wC(a,"mainVideoEntity");Ua=g.r(aa);for(nb=Ua.next();!nb.done;nb=Ua.next())ob=nb.value,fc=g.vC(ob.key).entityId,
fc!==a||y5(c,ob.actionProto)||ba.push(ob.key);return g.A(cb,Z4(b,{mode:"readwrite",dc:!0},function(Db){var pb=ba.map(function(zd){return V4(Db,zd)});
pb.push(V4(Db,pa,{Ut:!0}));pb.push(V4(Db,Ya,{Ut:!0}));return g.Dr.all(pb)}),7);
case 7:z5(G),h5(d,{entityKey:pa,failureReason:"OFFLINE_OPERATION_FAILURE_REASON_VIDEO_DELETED"}),h5(d,{entityKey:Ya,failureReason:"OFFLINE_OPERATION_FAILURE_REASON_VIDEO_DELETED"}),g.va(cb)}})},w_a=function(a,b,c,d){var e,f,h,l,m,n,p,q,t,u,x,y,z,D,H,G,L,aa,M,sa,xa,ba,pa,Ya,Ua,nb,ob,fc;
return g.B(function(cb){switch(cb.j){case 1:return e=g.wC(a,"mainPlaylistEntity"),f=g.wC(a,"ytMainChannelEntity"),g.A(cb,Z4(b,{mode:"readonly",dc:!0},function(Db){return g.Dr.all([Q4(Db,e,"mainPlaylistEntity"),Q4(Db,f,"ytMainChannelEntity"),R4(Db,"mainPlaylistEntity"),R4(Db,"ytMainChannelEntity"),R4(Db,"offlineOrchestrationActionWrapperEntity")])}),2);
case 2:h=cb.u;l=g.r(h);m=l.next().value;n=l.next().value;p=l.next().value;q=l.next().value;t=l.next().value;u=m;x=n;y=p;z=q;D=t;if(!u&&!x){cb.Oa(3);break}H=u?u_a(u):[];if(!x){G=[];cb.Oa(4);break}return g.A(cb,t_a(x,z),5);case 5:G=cb.u;case 4:return L=G,g.A(cb,r5(H.concat(L)),3);case 3:if(!u){cb.Oa(7);break}return g.A(cb,v_a(u,y),8);case 8:aa=cb.u;if(!aa){cb.Oa(7);break}M=g.r(aa);sa=M.next();case 10:if(sa.done){cb.Oa(7);break}xa=sa.value;ba=g.vC(xa).entityId;return g.A(cb,A5(ba,b,c,d),11);case 11:sa=
M.next();cb.Oa(10);break;case 7:pa=[];Ya=g.r(D);for(Ua=Ya.next();!Ua.done;Ua=Ya.next())nb=Ua.value,ob=g.vC(nb.key).entityId,ob!==a||y5(c,nb.actionProto)||pa.push(nb.key);fc=g.wC(a,"mainPlaylistEntity");return g.A(cb,Z4(b,{mode:"readwrite",dc:!0},function(Db){var pb=pa.map(function(zd){return V4(Db,zd)});
pb.push(V4(Db,fc,{Ut:!0}));return g.Dr.all(pb)}),0)}})},B5=function(a,b,c){var d,e,f,h,l,m;
return g.B(function(n){if(1==n.j)return g.A(n,Z4(a,{mode:"readwrite",dc:!0},function(p){var q=R4(p,"transfer"),t=R4(p,"offlineOrchestrationActionWrapperEntity");return g.Dr.all([q,t]).then(function(u){u=g.r(u);var x=u.next().value,y=u.next().value;u=x_a.map(function(L){return LZa(p,L)});
y=g.r(y);for(var z=y.next();!z.done;z=y.next()){z=z.value;var D=g.vC(z.actionProto.entityKey).entityType,H="ytMainDownloadedVideoEntity"===D;D="mainVideoEntity"===D;var G="OFFLINE_ORCHESTRATION_ACTION_TYPE_ADD"===z.actionProto.actionType;y5(b,z.actionProto)||H&&(!H||G)&&D&&(!D||G)||u.push(V4(p,z.key,{Ut:!0}))}return g.Dr.all(u).then(function(){return x})})}),2);
d=n.u;e=g.r(d);for(f=e.next();!f.done;f=e.next())h=f.value,z5(h),l=g.vC(h.key).entityId,m=g.wC(l,"ytMainDownloadedVideoEntity"),h5(c,{entityKey:m,failureReason:"OFFLINE_OPERATION_FAILURE_REASON_VIDEO_DELETED"});return g.A(n,s_a(),0)})},z_a=function(a,b,c,d){var e,f,h,l,m,n,p,q,t,u,x,y,z,D,H,G,L,aa,M,sa,xa,ba,pa,Ya;
return g.B(function(Ua){switch(Ua.j){case 1:return e=g.wC(a,"musicTrack"),f=g.wC(a,"musicArtist"),h=g.wC(a,"transfer"),g.A(Ua,Z4(b,{mode:"readonly",dc:!0},function(nb){return g.Dr.all([Q4(nb,e,"musicTrack"),Q4(nb,f,"musicArtist"),Q4(nb,h,"transfer"),R4(nb,"musicArtist"),R4(nb,"offlineOrchestrationActionWrapperEntity")])}),2);
case 2:l=Ua.u;m=g.r(l);n=m.next().value;p=m.next().value;q=m.next().value;t=m.next().value;u=m.next().value;x=n;y=p;z=q;D=t;H=u;if(!x&&!y){Ua.Oa(3);break}G=x?x5(x.thumbnailDetails):[];if(!y){L=[];Ua.Oa(4);break}return g.A(Ua,y_a(y,D),5);case 5:L=Ua.u;case 4:return aa=L,g.A(Ua,r5(G.concat(aa)),3);case 3:M=[];sa=g.wC(a,"musicTrack");xa=g.r(H);for(ba=xa.next();!ba.done;ba=xa.next())pa=ba.value,Ya=g.vC(pa.key).entityId,Ya!==a||y5(c,pa.actionProto)||M.push(pa.key);return g.A(Ua,Z4(b,{mode:"readwrite",
dc:!0},function(nb){var ob=M.map(function(fc){return V4(nb,fc)});
ob.push(V4(nb,sa,{Ut:!0}));return g.Dr.all(ob)}),7);
case 7:z5(z),h5(d,{entityKey:sa,failureReason:"OFFLINE_OPERATION_FAILURE_REASON_VIDEO_DELETED"}),g.va(Ua)}})},A_a=function(a,b,c){var d,e,f,h,l,m;
return g.B(function(n){if(1==n.j)return g.A(n,Z4(a,{mode:"readwrite",dc:!0},function(p){var q=R4(p,"transfer"),t=R4(p,"offlineOrchestrationActionWrapperEntity");return g.Dr.all([q,t]).then(function(u){u=g.r(u);var x=u.next().value,y=u.next().value;u=x_a.map(function(G){return LZa(p,G)});
y=g.r(y);for(var z=y.next();!z.done;z=y.next()){z=z.value;var D="musicTrack"===g.vC(z.actionProto.entityKey).entityType,H="OFFLINE_ORCHESTRATION_ACTION_TYPE_ADD"===z.actionProto.actionType;y5(b,z.actionProto)||D&&(!D||H)||u.push(V4(p,z.key,{Ut:!0}))}return g.Dr.all(u).then(function(){return x})})}),2);
d=n.u;e=g.r(d);for(f=e.next();!f.done;f=e.next())h=f.value,z5(h),l=g.vC(h.key).entityId,m=g.wC(l,"ytMainDownloadedVideoEntity"),h5(c,{entityKey:m,failureReason:"OFFLINE_OPERATION_FAILURE_REASON_VIDEO_DELETED"});return g.A(n,s_a(),0)})},y5=function(a,b){return a.actionType===b.actionType&&a.entityKey===b.entityKey},z5=function(a){if(a&&"TRANSFER_STATE_COMPLETE"!==a.transferState&&"TRANSFER_STATE_FAILED"!==a.transferState){var b=g.vC(a.key).entityId;
j5({transferStatusType:"TRANSFER_STATUS_TYPE_TERMINATED_BY_USER",statusType:"CANCELLED"},{videoId:b,nj:a})}},x5=function(a){if(!a||!a.thumbnails)return[];
var b=[];a=g.r(a.thumbnails);for(var c=a.next();!c.done;c=a.next())c=c.value,c.url&&b.push(c.url);return b},u_a=function(a,b){var c=[];
if(a.thumbnailStyleData){a=g.r(a.thumbnailStyleData);for(var d=a.next();!d.done;d=a.next()){var e=void 0,f=void 0,h=void 0;c=c.concat(x5(null==(e=d.value)?void 0:null==(f=e.value)?void 0:null==(h=f.collageThumbnail)?void 0:h.coverThumbnail))}}b=x5(b);return c.concat(b)},v_a=function(a,b){var c,d,e,f,h,l,m,n,p,q,t,u;
return g.B(function(x){c=[];if(a.videos){d=g.r(a.videos);for(e=d.next();!e.done;e=d.next())f=e.value,c.push(f);h=g.r(b);for(l=h.next();!l.done;l=h.next())if(m=l.value,m.key!==a.key&&(n=m.videos))for(p=g.r(n),q=p.next();!q.done;q=p.next())t=q.value,u=c.indexOf(t),-1!==u&&c.splice(u,1)}return x.return(c)})},t_a=function(a,b){var c,d,e,f,h,l,m,n;
return g.B(function(p){c=x5(a.avatar);d=g.r(b);for(e=d.next();!e.done;e=d.next())if(f=e.value,f.id!==a.id)for(h=g.r(x5(f.avatar)),l=h.next();!l.done;l=h.next())m=l.value,n=c.indexOf(m),-1!==n&&c.splice(n,1);return p.return(c)})},y_a=function(a,b){var c,d,e,f,h,l,m,n;
return g.B(function(p){c=x5(a.thumbnailDetails);d=g.r(b);for(e=d.next();!e.done;e=d.next())if(f=e.value,f.id!==a.id)for(h=g.r(x5(f.thumbnailDetails)),l=h.next();!l.done;l=h.next())m=l.value,n=c.indexOf(m),-1!==n&&c.splice(n,1);return p.return(c)})},C5=function(a){this.j=a},B_a=function(a,b){var c,d,e,f,h,l,m;
return g.B(function(n){switch(n.j){case 1:c=new Map,d=g.r(b),e=d.next();case 2:if(e.done){n.Oa(4);break}f=e.value;h=c;l=h.set;m=f;return g.A(n,a.u(f),5);case 5:l.call(h,m,n.u);e=d.next();n.Oa(2);break;case 4:return n.return(c)}})},D5=function(a,b,c,d){this.status=a;
this.j=b;this.u=c;this.failureReason=d},E5=function(a,b,c){this.j=a;
this.environmentData=b;this.B=c},E_a=function(a,b){var c,d,e,f,h,l,m;
return g.B(function(n){switch(n.j){case 1:c=b.entityKey;f=null==(d=b.actionMetadata)?void 0:null==(e=d.playbackDataActionMetadata)?void 0:e.isEnqueuedForExpiredStreamUrlRefetch;g.wa(n,2);var p;var q=null!=(p=b.actionMetadata)&&p.playbackDataActionMetadata?{maximumDownloadQuality:b.actionMetadata.playbackDataActionMetadata.maximumDownloadQuality}:void 0;return g.A(n,C_a(a,c,{isEnqueuedForExpiredStreamUrlRefetch:f,ZR:q}),4);case 4:return(h=n.u)?g.A(n,D_a(a,h,b),5):n.return(F5(b,!1,void 0,"OFFLINE_OPERATION_FAILURE_REASON_NETWORK_REQUEST_FAILED"));
case 5:return n.return(F5(b,!0,h.orchestrationActions));case 2:return l=g.za(n),m="OFFLINE_OPERATION_FAILURE_REASON_UNKNOWN",l instanceof g.wr&&"QUOTA_EXCEEDED"===l.type&&(m="OFFLINE_OPERATION_FAILURE_REASON_DATABASE_REQUEST_FAILED"),f5("PDE handleAdd error"),n.return(F5(b,!1,void 0,m))}})},F_a=function(a,b){var c,d,e,f,h,l,m,n,p,q,t,u,x,y,z;
return g.B(function(D){switch(D.j){case 1:return c=b.entityKey,g.A(D,Z4(a.j,{mode:"readonly",dc:!0},function(H){var G=Q4(H,c,"playbackData"),L=Q4(H,g.wC(g.vC(b.entityKey).entityId,"offlineVideoPolicy"),"offlineVideoPolicy");H=Q4(H,g.wC(g.vC(b.entityKey).entityId,"transfer"),"transfer");return g.Dr.all([G,L,H])}),2);
case 2:d=D.u;e=g.r(d);f=e.next().value;h=e.next().value;l=e.next().value;m=f;n=h;p=l;if(!m||!n)return D.return(F5(b,!0));q={lastPlayerResponseTimestampSeconds:m.playerResponseTimestamp,offlineToken:n.offlineToken};t={};if(null==(u=p)?0:u.maximumDownloadQuality)t.maximumDownloadQuality=p.maximumDownloadQuality;g.wa(D,3);return g.A(D,C_a(a,c,{refreshData:q,ZR:t}),5);case 5:return(x=D.u)?g.A(D,D_a(a,x,b),6):D.return(F5(b,!1,void 0,"OFFLINE_OPERATION_FAILURE_REASON_NETWORK_REQUEST_FAILED"));case 6:return D.return(F5(b,
!0,x.orchestrationActions));case 3:return y=g.za(D),z="OFFLINE_OPERATION_FAILURE_REASON_UNKNOWN",y instanceof g.wr&&"QUOTA_EXCEEDED"===y.type&&(z="OFFLINE_OPERATION_FAILURE_REASON_DATABASE_REQUEST_FAILED"),D.return(F5(b,!1,void 0,z))}})},C_a=function(a,b,c){var d,e,f;
return g.B(function(h){d=g.UH();var l=a.environmentData,m=c.refreshData,n=c.isEnqueuedForExpiredStreamUrlRefetch,p=c.ZR,q={entityKey:b};m&&(q.refreshData=m);n&&(q.isExpiredStreamUrlRefetch=n);p&&(q.downloadParameters=p);e={context:g.fI(l),signatureTimestamp:19151,videos:[q]};f=g.FH(G_a);return h.return(g.QF(d,e,f))})},D_a=function(a,b,c){var d;
return g.B(function(e){if(1==e.j){if(!b.frameworkUpdates||!b.frameworkUpdates.entityBatchUpdate)return e.return();if(!(b.frameworkUpdates.entityBatchUpdate.mutations&&0<b.frameworkUpdates.entityBatchUpdate.mutations.length&&"ENTITY_MUTATION_TYPE_DELETE"===b.frameworkUpdates.entityBatchUpdate.mutations[0].type))return e.Oa(2);d=g.vC(b.frameworkUpdates.entityBatchUpdate.mutations[0].entityKey).entityId;return g.A(e,A5(d,a.j,c,a.B),2)}return g.A(e,VZa(b.frameworkUpdates.entityBatchUpdate),0)})},F5=function(a,
b,c,d){return new D5(b?"OFFLINE_ORCHESTRATION_ACTION_RESULT_SUCCESS":"OFFLINE_ORCHESTRATION_ACTION_RESULT_FAILURE",t5(a),c,d)},G5=function(){C5.apply(this,arguments)},I_a=function(a,b){var c,d;
return g.B(function(e){switch(e.j){case 1:return c=t5(b),g.A(e,b5(a.j,b.entityKey,"transfer"),2);case 2:if(d=e.u)return e.return(new D5("OFFLINE_ORCHESTRATION_ACTION_RESULT_SUCCESS",c));g.wa(e,3);return g.A(e,H_a(a,b),5);case 5:g.ya(e,4);break;case 3:return g.za(e),e.return(new D5("OFFLINE_ORCHESTRATION_ACTION_RESULT_FAILURE",c,void 0,"OFFLINE_OPERATION_FAILURE_REASON_DATABASE_REQUEST_FAILED"));case 4:return e.return(new D5("OFFLINE_ORCHESTRATION_ACTION_RESULT_SUCCESS",c))}})},J_a=function(a,b){var c,
d;
return g.B(function(e){switch(e.j){case 1:return c=t5(b),g.A(e,b5(a.j,b.entityKey,"transfer"),2);case 2:d=e.u;if(!d||"TRANSFER_STATE_COMPLETE"!==d.transferState)return e.return(new D5("OFFLINE_ORCHESTRATION_ACTION_RESULT_SUCCESS",c));g.wa(e,3);return g.A(e,H_a(a,b,!0),5);case 5:g.ya(e,4);break;case 3:return g.za(e),e.return(new D5("OFFLINE_ORCHESTRATION_ACTION_RESULT_FAILURE",c,void 0,"OFFLINE_OPERATION_FAILURE_REASON_DATABASE_REQUEST_FAILED"));case 4:return e.return(new D5("OFFLINE_ORCHESTRATION_ACTION_RESULT_SUCCESS",
c))}})},H_a=function(a,b,c){c=void 0===c?!1:c;
var d,e,f,h,l,m;return g.B(function(n){if(1==n.j)return e=null==(d=b.actionMetadata)?void 0:d.transferEntityActionMetadata,l={key:b.entityKey,transferState:"TRANSFER_STATE_TRANSFER_IN_QUEUE",cotn:g.Cu(16),enqueuedTimestampMs:Date.now().toString(),maximumDownloadQuality:null==(f=e)?void 0:f.maximumDownloadQuality,preferredAudioTrack:null==(h=e)?void 0:h.preferredAudioTrack,transferRetryCount:0,isRefresh:c,hasLoggedFirstStarted:!1},m=g.vC(l.key).entityId,g.A(n,Z4(a.j,{mode:"readwrite",dc:!0},function(p){var q=
[];c&&q.push(V4(p,g.wC(m,"offlineVideoStreams")));q.push(T4(p,l,"transfer"));return g.Dr.all(q)}),2);
j5({transferStatusType:"TRANSFER_STATUS_TYPE_ENQUEUED",statusType:"ADDED_TO_QUEUE"},{videoId:m,nj:l});g.va(n)})},K_a=function(a,b,c){return new g.cD(a,{cotn:b,
raw_player_response:c,download_media:!0,start:Infinity,disable_watch_next:!0})},L_a=function(){return{priority:1,
retryScheduleIntervalsInSeconds:[1,2,4]}},H5=function(a,b,c,d,e,f,h,l,m,n,p){this.entityType=a;
this.actionId=b;this.action=c;this.parentActionId=d;this.rootActionId=void 0===e?b:e;this.childActionIds=f;this.prereqActionId=h;this.postreqActionIds=l;this.hasChildActionFailed=n;this.retryScheduleIndex=0;this.j=p||Date.now();this.retryScheduleIndex=m||0},I5=function(a){return{key:g.wC(a.actionId,"offlineOrchestrationActionWrapperEntity"),
actionProto:a.action,parentActionId:a.parentActionId,rootActionId:a.rootActionId,childActionIds:a.childActionIds,prereqActionId:a.prereqActionId,postreqActionIds:a.postreqActionIds,retryScheduleIndex:a.retryScheduleIndex,hasChildActionFailed:a.hasChildActionFailed,enqueueTimeSec:(a.j/1E3).toFixed()}},M_a=function(){this.j=new Map},N_a=function(){J5||(J5=new M_a);
return J5},O_a=function(a,b){return{eventType:{flowEventNamespace:"FLOW_EVENT_NAMESPACE_OFFLINE_ORCHESTRATION",
flowEventType:a},metadata:b,statusCode:void 0,csn:void 0,can:void 0}},P_a=function(a,b,c){if(!c){var d=void 0===d?!1:d;
c=a.j.get("FLOW_TYPE_OFFLINE_ORCHESTRATION");if(!c||d)c=g.Cu(16),a.j.set("FLOW_TYPE_OFFLINE_ORCHESTRATION",c)}a={flowNonce:c,flowType:"FLOW_TYPE_OFFLINE_ORCHESTRATION",flowEventType:b.eventType};b.metadata&&(a.flowMetadata=b.metadata);void 0!==b.statusCode&&(a.flowEventStatus=b.statusCode);b.csn&&(a.csn=b.csn);b.can&&(a.can=b.can);g.mr("flowEvent",a,void 0)},Q_a=function(a,b,c){if(!a.action.entityKey)throw Error("entityKey is missing.");
var d=g.vC(a.action.entityKey);a={entityType:d.gW,entityId:d.entityId,offlineOrchestrationActionType:a.action.actionType,orchestrationAction:{orchestrationActionId:a.actionId}};b&&(a.offlineOrchestrationActionResult=b.status,a.isRetryable=b.j);c&&(a.additionalOrchestrationActions=c.map(function(e){return{orchestrationActionId:e.actionId}}));
return a},K5=function(a,b){var c={offlineOrchestrationContext:Q_a(a)};
b=O_a(b,c);P_a(N_a(),b,a.rootActionId)},L5=function(a,b,c){c=void 0===c?[]:c;
b={offlineOrchestrationContext:Q_a(a,b,c)};b=O_a(3,b);P_a(N_a(),b,a.rootActionId)},R_a=function(){this.actions=[]},S_a=function(a,b){b=g.r(b);
for(var c=b.next();!c.done;c=b.next())c=c.value,K5(c,1),a.actions.push(c);a.actions.sort(a.j)},T_a=function(a,b){a=g.r(a.actions);
for(var c=a.next();!c.done;c=a.next())if(c.value.actionId===b)return!0;return!1},M5=function(a,b,c,d){g.I.call(this);
var e=this;this.u=a;this.Z=b;this.U=c;this.D=d;this.j=new R_a;this.P=new g.Hs;this.C=new g.K(function(){e.retry()});
this.I=NaN;g.J(this,this.C);this.J=$4(this.u,this.V.bind(this))},V_a=function(a,b,c,d){var e;
return g.B(function(f){if(1==f.j)return e=new M5(a,b,c,d),g.A(f,U_a(e),2);e.B?Promise.resolve():N5(e);return f.return(e)})},N5=function(a){var b,c,d,e,f,h,l,m,n,p,q,t,u,x,y;
return g.B(function(z){switch(z.j){case 1:if(a.B)throw Error("Already processing an action");if(a.isDisposed())return z.return();b=a.j.actions.shift();m_a(a.U,!b);if(void 0===b)return z.return();for(c=[b];;)if((d=a.j.actions[0])&&0===d.retryScheduleIndex&&d.entityType===b.entityType)c.push(a.j.actions.shift());else break;a.B=c;if(e=a.Z[b.entityType]){z.Oa(2);break}a.B=void 0;return g.A(z,N5(a),3);case 3:return z.return();case 2:f=g.r(c);for(h=f.next();!h.done;h=f.next())l=h.value,K5(l,2);g.wa(z,4,
5);return g.A(z,B_a(e,c.map(function(D){return D.action})),7);
case 7:m=z.u,n=g.r(c),h=n.next();case 8:if(h.done){z.Oa(5);break}p=h.value;q=m.get(p.action);return g.A(z,W_a(a,p,q),9);case 9:h=n.next();z.Oa(8);break;case 5:g.Aa(z);a.B=void 0;g.Ba(z,6);break;case 4:return t=g.za(z),f5("Orchestration error",t),g.wa(z,12),g.A(z,X_a(a,c),14);case 14:g.ya(z,5);break;case 12:u=g.za(z);f5("Orchestration retry error",u);x=g.r(c);for(h=x.next();!h.done;h=x.next())y=h.value,3>y.retryScheduleIndex&&S_a(a.j,[y]);z.Oa(5);break;case 6:return g.A(z,N5(a),0)}})},W_a=function(a,
b,c){var d,e,f,h,l,m;
return g.B(function(n){if(1==n.j){if("OFFLINE_ORCHESTRATION_ACTION_RESULT_SUCCESS"===c.status){h=void 0;try{h=null==(l=c.u)?void 0:l.map(function(p){return a.createAction(p,b)})}catch(p){return L5(b,c),m={entityKey:b.action.entityKey,
failureReason:"OFFLINE_OPERATION_FAILURE_REASON_UNSUPPORTED_ENTITY_FAILED"},h5(a.D,m),f5("Orchestration subactions creation error",p),n.return()}L5(b,c,h);return g.A(n,Z4(a.u,{mode:"readwrite",dc:!0},function(p){var q=[];if(h){var t=h.map(function(u){return I5(u)});
q.push(U4(p,t,"offlineOrchestrationActionWrapperEntity"))}t=I5(b);q.push(V4(p,t.key));return g.Dr.all(q)}),9)}if("OFFLINE_ORCHESTRATION_ACTION_RESULT_FAILURE"!==c.status)return n.Oa(0);
L5(b,c);if(c.j&&3>b.retryScheduleIndex+1)return g.A(n,X_a(a,[b]),0);e=(null==(d=c)?0:d.failureReason)?c.failureReason:"OFFLINE_OPERATION_FAILURE_REASON_UNKNOWN";f={entityKey:b.action.entityKey,failureReason:e};h5(a.D,f);f5("Orchestration result is not retryable, deleting action");return g.A(n,RZa(a.u,I5(b).key),0)}K5(b,4);g.va(n)})},O5=function(a,b){var c,d,e,f,h,l,m,n,p,q,t,u;
return g.B(function(x){c=[];d=Infinity;e=4E3;f=g.r(b);for(h=f.next();!h.done;h=f.next())l=h.value,m=Number(l.enqueueTimeSec),n=Y_a(m),p=l.retryScheduleIndex,q=null!=p&&0<p,0<n&&q?(d=Math.min(d,m),e=Math.min(n,e)):c.push(l);isFinite(d)&&(!a.C.isActive()||d<a.I)&&(a.I=d,a.C.start(e));a.P.mf()||(t=c.length,c=c.filter(function(y){var z;y=(null==(z=y.actionProto)?void 0:z.actionType)||"OFFLINE_ORCHESTRATION_ACTION_TYPE_UNKNOWN";return!Z_a.includes(y)}),u=c.length<t,!a.C.isActive()&&u&&a.C.start(1));
0<c.length&&$_a(a,c);return g.A(x,a.B?Promise.resolve():N5(a),0)})},b0a=function(a){var b,c,d,e,f,h,l;
return g.B(function(m){if(1==m.j)return g.A(m,a0a(a),2);b=m.u;c=[];d=g.r(b);for(e=d.next();!e.done;e=d.next())f=e.value,h=g.vC(f.key),l=h.entityId,T_a(a.j,l)||c.push(f);return g.A(m,O5(a,c),0)})},Y_a=function(a){a=1E3*a-Date.now();
return 4E3<a?4E3:a},X_a=function(a,b){var c,d,e;
return g.B(function(f){c=g.r(b);for(d=c.next();!d.done;d=c.next()){e=d.value;var h=void 0,l=void 0,m=(null==(l=e.action)?void 0:null==(h=l.actionMetadata)?void 0:h.retryScheduleIntervalsInSeconds)||[1,2,4];h=1;e.retryScheduleIndex<m.length&&(h=m[e.retryScheduleIndex]);e.j=1E3*h+Date.now();e.retryScheduleIndex++}return g.A(f,c0a(a,b),0)})},U_a=function(a){var b;
return g.B(function(c){if(1==c.j)return g.A(c,c5(a.u,"offlineOrchestrationActionWrapperEntity"),2);b=c.u;return g.A(c,O5(a,b),0)})},$_a=function(a,b){0!==b.length&&b.forEach(function(c){if(!c.key)throw Error("Entity key is required.");
if(!c.actionProto)throw Error("OfflineOrchestrationAction is required.");var d=g.vC(c.key),e=g.vC(c.actionProto.entityKey);c=new H5(e.entityType,d.entityId,c.actionProto,c.parentActionId,c.rootActionId,c.childActionIds,c.prereqActionId,c.postreqActionIds,c.retryScheduleIndex,c.hasChildActionFailed,1E3*Number(c.enqueueTimeSec));3>c.retryScheduleIndex&&S_a(a.j,[c])})},a0a=function(a,b){var c;
return g.B(function(d){if(1==d.j)return g.A(d,c5(a.u,"offlineOrchestrationActionWrapperEntity",b),2);c=d.u;return d.return(c.filter(WZa))})},c0a=function(a,b){if(0===b.length)return Promise.resolve([]);
b=b.map(function(c){return I5(c)});
return QZa(a.u,b)},d0a=function(){this.j=void 0},f0a=function(a,b){var c,d,e,f,h;
return g.B(function(l){c=b.videoId;d=b.S();e=!0;if(b.captionTracks.length)f=wZa(b),a.j=new g.TI(d,b,f);else if(b.Gc)h=g.iya(b),a.j=new g.VI(d,b.Gc,c,h,b.rl),e=b.rl;else return l.return();return l.return(new Promise(function(m){var n;null==(n=a.j)||n.Xu(function(){return g.B(function(p){if(1==p.j)return g.A(p,e0a(a,c,e),2);m();g.va(p)})})}))})},e0a=function(a,b,c){c=void 0===c?!0:c;
var d,e,f,h,l,m,n,p,q,t,u,x,y,z;return g.B(function(D){switch(D.j){case 1:if(!a.j)return D.return();d=[];e=g.QI(a.j.u,c);f=[];h={};l=g.r(e.entries());for(m=l.next();!m.done;h={JD:h.JD},m=l.next())n=m.value,p=g.r(n),q=p.next().value,t=p.next().value,h.JD=q,u=t,x=a.j.xr(u,"json3"),y=g.jq(x,{withCredentials:!0,format:"RAW"},3,500).then(function(H){return function(G){G={metadata:g.OC(e[H.JD]),trackData:G.xhr.responseText};f.push(G)}}(h)).Hi(function(H){f5("Caption fetch error",H)}),d.push(y);
return g.A(D,xZa(d),2);case 2:return g.wa(D,3),g.A(D,$Za(b,f),5);case 5:g.ya(D,0);break;case 3:z=g.za(D),f5("Caption DB transaction error",z),g.va(D)}})},g0a=function(a){var b;
return g.B(function(c){if(1==c.j)return g.A(c,a_a(a),2);b=c.u;return c.return(!!b&&0<b.length)})},h0a=function(a,b){this.api=a;
this.j=b;this.logger=new g.lO("woffle");this.u=!1},i0a=function(a){return g.B(function(b){return b.return(b_a(a))})},j0a=function(a){var b;
return g.B(function(c){if(1==c.j)return g.A(c,g.Uwa(a),2);b=c.u;return c.return(b.filter(function(d){return!!d.url}).map(function(d){return d.url}))})},P5=function(a,b){var c=g.HC(b);
if(1===c||0===c)return Promise.resolve();(c=k0a(a,b))&&c.stopVideo();a.B=0;return i0a(b)},Q5=function(a,b,c,d){c=void 0===c?!1:c;
d=void 0===d?!0:d;var e="string"===typeof b?b:b.videoDetails.videoId;2===g.HC(e)&&((b=k0a(a,e))?b.stopVideo():a.logger.info(function(){return"Corresponding player for "+e+" not found. Pausing anyway"}),g.IC(e,2),a.B=2,c?l0a(a.j):d&&m0a(a.j))},k0a=function(a,b){var c;
return(null==(c=a.player)?void 0:c.getVideoData().videoId)===b?a.player:null},n0a=function(a){switch(a){case "HD_1080":return"hd1080";
case "HD":return"hd720";case "SD":return"large";case "LD":return"tiny";default:return"hd720"}},R5=function(a){g.I.call(this);
this.j=a;this.u=$4(this.j,this.B.bind(this))},o0a=function(a,b){var c,d,e,f,h,l,m;
return g.B(function(n){switch(n.j){case 1:if(0===b.length)return n.return([]);c=b.map(function(p){return g.wC(p,"transfer")});
return g.A(n,c5(a.j,"transfer",c),2);case 2:d=n.u;e=d.filter(WZa).map(function(p){return g.vC(p.key).entityId});
f=b.filter(function(p){return-1===e.indexOf(p)});
if(0===f.length)return n.return([]);h=g.r(f);l=h.next();case 3:if(l.done){n.Oa(5);break}m=l.value;return g.A(n,i0a(m),4);case 4:l=h.next();n.Oa(3);break;case 5:return n.return(f)}})},q0a=function(a,b,c,d,e,f){var h,l,m;
return g.B(function(n){h="STREAM_TYPE_UNKNOWN";c.video&&c.audio?(h="STREAM_TYPE_AUDIO_AND_VIDEO",f5("unexpected stream type")):c.video&&!c.audio?h="STREAM_TYPE_VIDEO":!c.video&&c.audio&&(h="STREAM_TYPE_AUDIO");l=g.wC(b,"offlineVideoStreams");m={numBytesDownloaded:e.toFixed(),numTotalBytes:f.toFixed(),streamType:h,streamState:"DOWNLOAD_STREAM_STATE_IN_PROGRESS",formatStreamBytes:JSON.stringify(d),itag:"STREAM_TYPE_AUDIO_AND_VIDEO"===h?Number(c.Tb()):void 0};return g.A(n,Z4(a,{mode:"readwrite",dc:!0},
function(p){var q=Q4(p,l,"offlineVideoStreams"),t=Q4(p,g.wC(b,"transfer"),"transfer");return g.Dr.all([q,t]).then(function(u){var x=g.r(u);u=x.next().value;x=x.next().value;if(!x)return V4(p,l).then(function(){});
u=[T4(p,p0a(u,d,m,l),"offlineVideoStreams")];x.offlineVideoStreams||(x.offlineVideoStreams=[]);-1===x.offlineVideoStreams.indexOf(l)&&(x.offlineVideoStreams.push(l),u.push(T4(p,x,"transfer")));return g.Dr.all(u)})}),0)})},r0a=function(a,b){var c,d,e,f,h;
return g.B(function(l){if(1==l.j)return c=g.wC(b,"offlineVideoStreams"),g.A(l,b5(a,c,"offlineVideoStreams"),2);d=l.u;if(!d||!d.streamsProgress)return l.return();e=g.r(d.streamsProgress);for(f=e.next();!f.done;f=e.next())h=f.value,h.streamState="DOWNLOAD_STREAM_STATE_COMPLETE",h.numTotalBytes!==h.numBytesDownloaded&&(h.numBytesDownloaded=h.numTotalBytes);return g.A(l,a5(a,d,"offlineVideoStreams"),0)})},p0a=function(a,b,c,d){if(a&&a.streamsProgress){d=a;
a:{b=b.itag+";"+b.xtags;for(var e=a.streamsProgress,f=0;f<e.length;f++){var h=JSON.parse(e[f].formatStreamBytes);if(h.itag+";"+h.xtags===b){e[f]=c;c=e;break a}}e.push(c);c=e}d.streamsProgress=c}else a={key:d,streamsProgress:[c]};return a},S5=function(a,b,c,d){g.I.call(this);
var e=this;this.u=a;this.api=b;this.xa=c;this.ma=d;this.D=new g.Hs;this.C=new g.K(function(){e.j&&"TRANSFER_STATE_TRANSFERRING"===e.j.transferState&&e.D.mf()&&(3>(e.j.transferRetryCount||0)?Q5(e.I,e.B,!1,!1):P5(e.I,e.B.videoDetails.videoId),e.Xr("TRANSFER_FAILURE_REASON_TIMEOUT_NO_PROGRESS"))});
this.U=0;this.ea=new g.ez(this);this.J=$4(this.u,this.NS.bind(this));this.I=new h0a(b,this);this.Ga=new d0a;this.P=new R5(this.u);this.Z=this.D.Ka("publicytnetworkstatus-online",this.pz.bind(this));this.V=this.D.Ka("publicytnetworkstatus-offline",this.e0.bind(this));g.J(this,this.ea);this.ea.N(b,"offlinetransferpause",this.f0);this.Ca=g.Zz(this.api.S().experiments,"web_player_transfer_timeout_threshold_ms")},s0a=function(a){return g.B(function(b){if(1==b.j)b=g.A(b,ZZa(),2);
else{var c=a.P;var d=g.GC();d=Object.keys(d);c=o0a(c,d);b=g.A(b,c,0)}return b})},U5=function(a,b){b=void 0===b?!1:b;
var c;return g.B(function(d){if(1==d.j){if(a.j)throw Error("Already downloading a video");return g.A(d,t0a(a),2)}return 4!=d.j?(c=d.u,n_a(a.xa,!c),c&&a.D.mf()?b?g.A(d,new Promise(function(e){g.bq(e,1E3)}),4):d.Oa(4):(!c&&a.j&&T5(a),d.Oa(0))):g.A(d,u0a(a,c),0)})},v0a=function(a){return g.B(function(b){if(1==b.j)return a.B?g.A(b,P5(a.I,a.B.videoDetails.videoId),3):b.Oa(0);
T5(a);g.va(b)})},w0a=function(a,b){var c,d,e;
return g.B(function(f){switch(f.j){case 1:return g.wa(f,2),(c=!!b.captionTracks.length||!!b.Gc)?g.A(f,g0a(b.videoId),4):f.return();case 4:return(d=f.u)?f.return():g.A(f,f0a(a.Ga,b),5);case 5:g.ya(f,0);break;case 2:e=g.za(f),f5("Caption downloading error",e,b.cotn),g.va(f)}})},u0a=function(a,b){var c,d,e,f,h;
return g.B(function(l){switch(l.j){case 1:return a.j=b,c=g.vC(a.j.key),"TRANSFER_STATE_TRANSFERRING"===a.j.transferState&&j5({transferStatusType:"TRANSFER_STATUS_TYPE_RESUME_PROCESSING",statusType:"OFFLINING_RETRIED"},{videoId:c.entityId,nj:a.j}),g.A(l,V5(a),2);case 2:return d=null,g.wa(l,3),g.A(l,x0a(a,b),5);case 5:d=l.u;a.B=d;g.ya(l,4);break;case 3:return e=g.za(l),f5("error getting player response",e,b.cotn),g.A(l,a.Xr("TRANSFER_FAILURE_REASON_INTERNAL"),6);case 6:return l.return();case 4:return f=
K_a(a.api.S(),b.cotn,d),g.A(l,w0a(a,f),7);case 7:return h=f,g.A(l,j0a(f.videoId),8);case 8:h.Sm=l.u;var m=a.I,n=b.maximumDownloadQuality;f.getPlayerResponse();g.IC(f.videoId,2);m.B=2;m.u=!1;var p;null==(p=m.player)||p.dispose();m.player=m.api.So(9,f);p={};g.eu(m.player,(p.localmediachange=m.tC,p.signatureexpired=m.gI,p.statechange=m.UY,p),m);n=n0a(n);m.K("hoffle_lmqf_killswitch")||g.ANa(m.player,g.Gw(n,n,!0,"m"),!1);g.AN(m.player,!1);W5(a);g.va(l)}})},t0a=function(a){var b,c;
return g.B(function(d){if(1==d.j)return g.A(d,c5(a.u,"transfer"),2);b=d.u;c=b.filter(y0a).sort(z0a);return 0===c.length?d.return():d.return(c[0])})},V5=function(a){return g.B(function(b){W5(a);
return g.A(b,X5(a,"TRANSFER_STATE_TRANSFERRING"),0)})},l0a=function(a){var b;
g.B(function(c){if(1==c.j)return a.C.stop(),g.A(c,X5(a,"TRANSFER_STATE_PAUSED_BY_USER"),2);b=g.vC(a.j.key);p_a({videoId:b.entityId,nj:a.j});T5(a);U5(a);g.va(c)})},m0a=function(a){g.B(function(b){if(1==b.j)return a.C.stop(),g.A(b,X5(a,"TRANSFER_STATE_TRANSFER_IN_QUEUE"),2);
T5(a);g.va(b)})},A0a=function(a){var b,c,d;
g.B(function(e){switch(e.j){case 1:a.C.stop();if(!a.j||!a.B){e.Oa(2);break}b=K_a(a.api.S(),a.j.cotn,a.B);return g.A(e,w0a(a,b),2);case 2:return g.A(e,X5(a,"TRANSFER_STATE_COMPLETE","DOWNLOAD_STREAM_STATE_COMPLETE"),4);case 4:return c=g.vC(a.j.key),d=c.entityId,g.A(e,r0a(a.u,d),5);case 5:j5({transferStatusType:"TRANSFER_STATUS_TYPE_COMPLETED",statusType:"SUCCESS"},{videoId:d,nj:a.j}),T5(a),U5(a),g.va(e)}})},C0a=function(a,b,c){var d;
g.B(function(e){switch(e.j){case 1:if("TRANSFER_STATE_TRANSFERRING"===a.j.transferState){e.Oa(2);break}return g.A(e,V5(a),2);case 2:d=Date.now();if(!(1E3<d-a.U)){e.Oa(4);break}a.U=d;return g.A(e,q0a(a.u,c.videoId,c.u,c.formatStream,c.bytesDownloaded,c.j),5);case 5:if(a.j.hasLoggedFirstStarted){o_a({videoId:b,nj:a.j},c.bytesDownloaded,c.j);e.Oa(4);break}a.j.hasLoggedFirstStarted=!0;return g.A(e,B0a(a),7);case 7:o_a({videoId:b,nj:a.j},c.bytesDownloaded,c.j,!0);case 4:W5(a),g.va(e)}})},D0a=function(a){var b=
3>(a.j.transferRetryCount||0);
b&&(a=a.j,a.transferRetryCount=(a.transferRetryCount||0)+1);return b},E0a=function(a,b){b=void 0===b?"TRANSFER_FAILURE_REASON_UNKNOWN":b;
var c,d;return g.B(function(e){if(1==e.j)return c="OFFLINE_OPERATION_FAILURE_REASON_UNKNOWN","TRANSFER_FAILURE_REASON_NETWORK"===b?c="OFFLINE_OPERATION_FAILURE_REASON_NETWORK_REQUEST_FAILED":"TRANSFER_FAILURE_REASON_FILESYSTEM_WRITE"===b&&(c="OFFLINE_OPERATION_FAILURE_REASON_DATABASE_REQUEST_FAILED"),g.A(e,X5(a,"TRANSFER_STATE_FAILED","DOWNLOAD_STREAM_STATE_ERROR_STREAMS_MISSING",b),2);h5(a.ma,{entityKey:a.j.key,failureReason:c});d=g.vC(a.j.key).entityId;var f={videoId:d,nj:a.j},h=b,l={transferStatusType:"TRANSFER_STATUS_TYPE_TERMINATED_WITH_FAILURE",
statusType:"FAILED"};h&&(l.transferFailureReason=h,l.failureReason=q_a(h));j5(l,f);g.va(e)})},X5=function(a,b,c,d){var e;
return g.B(function(f){if(1==f.j)return a.j.transferState=b,a.j.failureReason=d,g.wa(f,2),g.A(f,B0a(a,function(h){return c?R4(h,"offlineVideoStreams",a.j.offlineVideoStreams).then(function(l){for(var m=g.r(l),n=m.next();!n.done;n=m.next())if((n=n.value)&&n.streamsProgress){n=g.r(n.streamsProgress);for(var p=n.next();!p.done;p=n.next())p.value.streamState=c}return U4(h,l.filter(function(q){return!!q}),"offlineVideoStreams")}):g.Dr.resolve(void 0)}),4);
if(2!=f.j)return g.ya(f,0);e=g.za(f);return e instanceof g.wr&&"QUOTA_EXCEEDED"===e.type?g.A(f,a.Xr("TRANSFER_FAILURE_REASON_FILESYSTEM_WRITE"),0):f.Oa(0)})},B0a=function(a,b){var c;
return g.B(function(d){if(!a.j)return d.return();c=a.j;return g.A(d,Z4(a.u,{mode:"readwrite",dc:!0},function(e){var f=[T4(e,c,"transfer")];b&&f.push(b(e));return g.Dr.all(f)}),0)})},T5=function(a){a.j=void 0;
a.B=void 0;a.C.stop()},x0a=function(a,b){var c,d,e,f,h;
return g.B(function(l){if(1==l.j)return c=g.vC(b.key),d=c.entityId,e=g.wC(d,"playbackData"),g.A(l,b5(a.u,e,"playbackData"),2);f=l.u;if(null==(h=f)?0:h.playerResponseJson)return l.return(JSON.parse(f.playerResponseJson));throw Error("No PlayerResponse found");})},W5=function(a){a.C.start(a.Ca||18E5)},y0a=function(a){return void 0!==Y5[a.transferState]},z0a=function(a,b){var c=Y5[a.transferState],d=Y5[b.transferState];
return c!==d?c-d:Number(a.enqueuedTimestampMs)-Number(b.enqueuedTimestampMs)},Z5=function(a,b){var c=this;
this.environmentData=a;this.api=b;this.P=new g.Hs;this.B=new j_a(function(){return F0a(c)},function(){G0a(c)},this.api.wp(),this.api.K.bind(this.api));
this.u=new g5(this.api);this.C=new g.ji;k_a(this.B)},F0a=function(a){return g.B(function(b){a.api.Ia("onOrchestrationBecameLeader");
a.j&&a.D||H0a(a).then(a.C.resolve).catch(a.C.reject);var c=a.C.promise;return g.A(b,c,0)})},H0a=function(a){var b,c,d;
return g.B(function(e){if(1==e.j)return g.A(e,e5(),2);if(3!=e.j){b=e.u;if(!b)return f5("PES is undefined"),e.return();a.j=new S5(b,a.api,a.B,a.u);c=a.Kx(b);d=a;return g.A(e,V_a(b,c,a.B,a.u),3)}d.D=e.u;return g.A(e,I0a(a),0)})},I0a=function(a){var b;
return g.B(function(c){switch(c.j){case 1:if(!a.j)return f5("transferManager is undefined"),c.return();if(a.j.j){c.Oa(2);break}return g.A(c,U5(a.j),2);case 2:return g.A(c,a.mz(),4);case 4:return a.J=g.cq(function(){a.mz()},9E5),g.cr(g.er(),function(){return a.YI()}),g.A(c,e5(),5);
case 5:return b=c.u,g.A(c,f_a(b),6);case 6:l_a(a.B),g.va(c)}})},G0a=function(a){var b,c;
g.B(function(d){if(1==d.j)return a.j||a.D?g.A(d,a.C.promise,2):d.return();void 0!==a.J&&(window.clearInterval(a.J),a.J=void 0);null==(b=a.j)||b.dispose();a.j=void 0;null==(c=a.D)||c.dispose();a.D=void 0;a.api.Ia("onOrchestrationLostLeader");a.C=new g.ji;g.va(d)})},J0a=function(){var a,b,c,d,e,f;
return g.B(function(h){switch(h.j){case 1:return g.A(h,e5(),2);case 2:a=h.u;if(!a)return h.return([]);b=Date.now()/1E3;return g.A(h,c5(a,"offlineVideoPolicy"),3);case 3:c=h.u,d=g.r(c),e=d.next();case 4:if(e.done){h.Oa(6);break}f=e.value;if(!(f.expirationTimestamp&&Number(f.expirationTimestamp)<b)){h.Oa(5);break}f.action="OFFLINE_VIDEO_POLICY_ACTION_DISABLE";return g.A(h,a5(a,f,"offlineVideoPolicy"),5);case 5:e=d.next();h.Oa(4);break;case 6:return h.return(c.map(function(l){return l.key}))}})},$5=
function(a,b,c,d,e){var f,h,l;
return g.B(function(m){if(1==m.j)return g.A(m,e5(),2);f=m.u;if(!f)return m.return([]);h=b.map(function(n){var p=g.wC(n,c);p={actionType:d,entityKey:p,actionMetadata:Object.assign({},L_a(),e)};"OFFLINE_ORCHESTRATION_ACTION_TYPE_REFRESH"!==d&&(p.actionMetadata.priority=0);n=new H5(c,n,p);return I5(n)});
l=QZa(f,h);k_a(a.B);return m.return(l)})},a6=function(a){var b,c,d,e,f;
return g.B(function(h){switch(h.j){case 1:return b=g.UH(),c=c_a(a),d=g.FH(K0a),g.wa(h,2),g.A(h,g.QF(b,c,d),4);case 4:e=h.u;g.ya(h,3);break;case 2:throw f=g.za(h),f5("GetOffline fetch request error",f),Error("GetOffline fetch request error");case 3:if(!e)throw Error("Network request failed");if(!e.videos||!e.videos.length)throw Error("No data");return h.return(e.videos.map(function(l){return l.offlineVideoData}))}})},L0a=function(a){var b,c,d,e,f;
return g.B(function(h){switch(h.j){case 1:return b=g.UH(),c=d_a(a),d=g.FH(K0a),g.wa(h,2),g.A(h,g.QF(b,c,d),4);case 4:e=h.u;g.ya(h,3);break;case 2:throw f=g.za(h),f5("GetOffline fetch request error for playlist",f),Error("GetOffline fetch request error for playlist");case 3:if(!e)throw Error("Network request failed");if(!e.playlists||!e.playlists.length)throw Error("No data");return h.return(e.playlists.map(function(l){return l.offlinePlaylistData}))}})},N0a=function(){var a,b,c,d,e;
return g.B(function(f){switch(f.j){case 1:return a=g.UH(),b={context:g.KF(),browseId:"FEdownloads",browseRequestSupportedMetadata:{downloadsBrowseParams:{offlineFeatureSettingState:{isSdEnabled:!1}}}},c=g.FH(M0a),g.wa(f,2),g.A(f,g.QF(a,b,c),4);case 4:d=f.u;g.ya(f,3);break;case 2:throw e=g.za(f),f5("DPS fetch request error for smart downloads",e),Error("DPS fetch request error for smart downloads");case 3:if(!d)throw Error("Network request failed");return f.return(d)}})},b6=function(a,b){this.j=a;
this.B=b},P0a=function(a,b){var c,d,e,f,h,l,m,n,p,q,t,u,x;
return g.B(function(y){switch(y.j){case 1:return c=t5(b),d=g.vC(b.entityKey),e=d.entityId,f=[],g.wa(y,2),g.A(y,O0a(a,e),4);case 4:f=y.u;g.ya(y,3);break;case 2:return h=g.za(y),l="OFFLINE_OPERATION_FAILURE_REASON_UNKNOWN",h instanceof g.wr&&"QUOTA_EXCEEDED"===h.type&&(l="OFFLINE_OPERATION_FAILURE_REASON_DATABASE_REQUEST_FAILED"),y.return(new D5("OFFLINE_ORCHESTRATION_ACTION_RESULT_FAILURE",c,void 0,l));case 3:m=[];if(null==(n=f)?0:n.length)for(p=g.r(f),q=p.next();!q.done;q=p.next())t=q.value,u=t.offlineVideoData,
x=void 0,(null==(x=u)?0:x.videoId)&&m.push(c6("OFFLINE_ORCHESTRATION_ACTION_TYPE_ADD",u.videoId,d6(b,u)));return y.return(new D5("OFFLINE_ORCHESTRATION_ACTION_RESULT_SUCCESS",c,m))}})},Q0a=function(a,b){var c,d,e,f,h,l,m,n,p,q,t,u,x,y,z,D,H,G,L,aa,M,sa,xa,ba,pa,Ya,Ua,nb,ob,fc,cb,Db,pb,zd,Oe,Sf,wf,Ag,pe,Xb,Tf,xf;
return g.B(function(Md){switch(Md.j){case 1:return c=t5(b),d=b.entityKey,e=g.vC(d).entityId,g.A(Md,b5(a.j,d,"mainPlaylistEntity"),2);case 2:f=Md.u;if(!f)return Md.return(new D5("OFFLINE_ORCHESTRATION_ACTION_RESULT_SUCCESS",c));h=[];l=new Map;m=[];g.wa(Md,3);return g.A(Md,O0a(a,e),5);case 5:h=Md.u;g.ya(Md,4);break;case 3:return n=g.za(Md),n instanceof Error&&"No data"===n.message?g.A(Md,w_a(e,a.j,b,a.B),4):(p="OFFLINE_OPERATION_FAILURE_REASON_UNKNOWN",n instanceof g.wr&&"QUOTA_EXCEEDED"===n.type&&
(p="OFFLINE_OPERATION_FAILURE_REASON_DATABASE_REQUEST_FAILED"),Md.return(new D5("OFFLINE_ORCHESTRATION_ACTION_RESULT_FAILURE",c,void 0,p)));case 4:q=[];t=new Map;if(null==(u=h)?0:u.length)for(x=g.r(h),y=x.next();!y.done;y=x.next())z=y.value,D=z.offlineVideoData,H=void 0,(null==(H=D)?0:H.videoId)&&t.set(D.videoId,D);if(null==(G=f)?0:null==(L=G.videos)?0:L.length)for(aa=g.r(f.videos),M=aa.next();!M.done;M=aa.next())sa=M.value,xa=g.vC(sa).entityId,t.has(xa)?(l.set(xa,t.get(xa)),t.delete(xa)):m.push(xa);
ba=g.r(t.entries());for(pa=ba.next();!pa.done;pa=ba.next())Ya=pa.value,Ua=g.r(Ya),nb=Ua.next().value,ob=Ua.next().value,fc=nb,cb=ob,q.push(c6("OFFLINE_ORCHESTRATION_ACTION_TYPE_ADD",fc,d6(b,cb)));Db=g.r(l.entries());for(pb=Db.next();!pb.done;pb=Db.next())zd=pb.value,Oe=g.r(zd),Sf=Oe.next().value,wf=Oe.next().value,Ag=Sf,pe=wf,q.push(c6("OFFLINE_ORCHESTRATION_ACTION_TYPE_REFRESH",Ag,d6(b,pe)));Xb=g.r(m);for(Tf=Xb.next();!Tf.done;Tf=Xb.next())xf=Tf.value,q.push(c6("OFFLINE_ORCHESTRATION_ACTION_TYPE_DELETE",
xf));return Md.return(new D5("OFFLINE_ORCHESTRATION_ACTION_RESULT_SUCCESS",c,q))}})},R0a=function(a,b){var c,d;
return g.B(function(e){switch(e.j){case 1:return c=t5(b),g.wa(e,2),d=g.vC(b.entityKey).entityId,"!*$_ALL_ENTITIES_!*$"===d?g.A(e,B5(a.j,b,a.B),5):g.A(e,w_a(d,a.j,b,a.B),5);case 5:g.ya(e,3);break;case 2:return g.za(e),e.return(new D5("OFFLINE_ORCHESTRATION_ACTION_RESULT_FAILURE",c,void 0,"OFFLINE_OPERATION_FAILURE_REASON_DATABASE_REQUEST_FAILED"));case 3:return e.return(new D5("OFFLINE_ORCHESTRATION_ACTION_RESULT_SUCCESS",c))}})},O0a=function(a,b){var c,d,e,f,h;
return g.B(function(l){switch(l.j){case 1:return g.A(l,L0a([b]),2);case 2:return c=l.u,g.A(l,S0a(a,c[0]),3);case 3:return d=l.u,e=d.mainPlaylistEntity,f=d.k0,h=u_a(e,f.avatar),g.A(l,s5(h),4);case 4:return l.return(c[0].videos)}})},S0a=function(a,b){var c=void 0,d,e,f,h,l,m,n,p,q,t,u,x,y;
return g.B(function(z){if(1==z.j){if(!(b&&b.playlistId&&b.channel&&b.channel.offlineChannelData))throw Error("Invalid OfflinePlaylistData");c||(c=Date.now().toString());d=b.videos;e=[];f=[];if(d)for(h=g.r(d),l=h.next();!l.done;l=h.next()){m=l.value;n=m.offlineVideoData;if(!n||!n.videoId)throw Error("Invalid offlineVideoData");p=n.videoId;q={id:g.wC(p,"mainPlaylistVideoEntity"),video:g.wC(p,"mainVideoEntity")};e.push(q);f.push(q.id)}t=b.playlistId;u=b.channel.offlineChannelData;x=T0a(g.wC(t,"ytMainChannelEntity"),
u);y={key:g.wC(t,"mainPlaylistEntity"),playlistId:t,channelOwner:x.id,videos:f,title:b.title,thumbnailStyleData:U0a(b),visibility:V0a(b)};return g.A(z,Z4(a.j,{mode:"readwrite",dc:!0},function(D){for(var H=T4(D,y,"mainPlaylistEntity"),G=T4(D,x,"ytMainChannelEntity"),L=[],aa=g.r(e),M=aa.next();!M.done;M=aa.next())L.push(T4(D,M.value,"mainPlaylistVideoEntity"));return g.Dr.all([H,G].concat(g.v(L)))}),2)}return z.return({mainPlaylistEntity:y,
k0:x,Fka:e})})},c6=function(a,b,c){b=g.wC(b,"mainVideoEntity");
c=Object.assign({},c,{priority:0,retryScheduleIntervalsInSeconds:W0a});return{actionType:a,entityKey:b,actionMetadata:c}},T0a=function(a,b){if(!(b.channelId&&b.title&&b.thumbnail))throw Error("Invalid OfflineChannelData");
return{id:a,channelId:b.channelId,title:b.title,avatar:b.thumbnail}},U0a=function(a){var b=[],c=a.videos;
c&&0<c.length&&b.push({key:Number("PLAYLIST_THUMBNAIL_STYLE_FIRST_VIDEO"),value:{collageThumbnail:{coverThumbnail:c[0].offlineVideoData.thumbnail}}});if((a=a.additionalMetadadatas)&&0<a.length)for(a=g.r(a),c=a.next();!c.done;c=a.next()){var d=c.value.offlineBundleItemPlaylistData,e=void 0;c=null==(e=d)?void 0:e.style;e=void 0;d={collageThumbnail:{coverThumbnail:null==(e=d)?void 0:e.coverThumbnail}};switch(c){case "BUNDLE_ITEM_STYLE_UNSPECIFIED":b.push({key:Number("PLAYLIST_THUMBNAIL_STYLE_UNKNOWN"),
value:d});break;case "BUNDLE_ITEM_STYLE_TWO_BY_TWO":b.push({key:Number("PLAYLIST_THUMBNAIL_STYLE_TWO_BY_TWO"),value:d});break;case "BUNDLE_ITEM_STYLE_ONE_AND_TWO_AVATAR":b.push({key:Number("PLAYLIST_THUMBNAIL_STYLE_ONE_AND_TWO_AVATAR"),value:d});break;case "BUNDLE_ITEM_STYLE_ONE_AND_TWO":b.push({key:Number("PLAYLIST_THUMBNAIL_STYLE_ONE_AND_TWO"),value:d})}}return b},V0a=function(a){switch(a.privacy){case "PRIVATE":return"PLAYLIST_VISIBILITY_PRIVATE";
case "PUBLIC":return"PLAYLIST_VISIBILITY_PUBLIC";case "UNLISTED":return"PLAYLIST_VISIBILITY_UNLISTED";default:return"PLAYLIST_VISIBILITY_UNKNOWN"}},d6=function(a,b){b={offlineVideoData:b};
var c;if(null==(c=a.actionMetadata)?0:c.mainPlaylistEntityActionMetadata)b.maximumDownloadQuality=a.actionMetadata.mainPlaylistEntityActionMetadata.maximumDownloadQuality;return{mainVideoEntityActionMetadata:b}},e6=function(a,b){this.j=a;
this.B=b},Z0a=function(a,b){var c,d,e,f,h,l,m,n;
return g.B(function(p){switch(p.j){case 1:return c=t5(b),d=g.vC(b.entityKey),e=d.entityId,g.wa(p,2),g.A(p,X0a(a,e,void 0,null==(f=b.actionMetadata)?void 0:null==(h=f.mainVideoEntityActionMetadata)?void 0:h.offlineVideoData),4);case 4:g.ya(p,3);break;case 2:return l=g.za(p),m="OFFLINE_OPERATION_FAILURE_REASON_UNKNOWN",l instanceof g.wr&&"QUOTA_EXCEEDED"===l.type&&(m="OFFLINE_OPERATION_FAILURE_REASON_DATABASE_REQUEST_FAILED"),p.return(new D5("OFFLINE_ORCHESTRATION_ACTION_RESULT_FAILURE",c,void 0,m));
case 3:var q;var t=null!=(q=b.actionMetadata)&&q.mainVideoEntityActionMetadata?{playbackDataActionMetadata:{maximumDownloadQuality:b.actionMetadata.mainVideoEntityActionMetadata.maximumDownloadQuality}}:void 0;n=Y0a("OFFLINE_ORCHESTRATION_ACTION_TYPE_ADD",e,t);return p.return(new D5("OFFLINE_ORCHESTRATION_ACTION_RESULT_SUCCESS",c,[n]))}})},$0a=function(a,b){var c,d,e,f,h,l,m,n,p,q,t;
return g.B(function(u){switch(u.j){case 1:return c=t5(b),d=g.vC(b.entityKey),e=d.entityId,g.A(u,b5(a.j,b.entityKey,"mainVideoEntity"),2);case 2:f=u.u;if(!f){h=void 0;u.Oa(3);break}return g.A(u,b5(a.j,f.downloadState,"mainVideoDownloadStateEntity"),4);case 4:h=u.u;case 3:l=h;if(!f||!l)return u.return(new D5("OFFLINE_ORCHESTRATION_ACTION_RESULT_SUCCESS",c));g.wa(u,5);return g.A(u,X0a(a,e,l.addedTimestampMillis,null==(n=b.actionMetadata)?void 0:null==(p=n.mainVideoEntityActionMetadata)?void 0:p.offlineVideoData),
7);case 7:m=Y0a("OFFLINE_ORCHESTRATION_ACTION_TYPE_REFRESH",e);g.ya(u,6);break;case 5:return q=g.za(u),q instanceof Error&&"No data"===q.message?g.A(u,A5(e,a.j,b,a.B),6):(t="OFFLINE_OPERATION_FAILURE_REASON_UNKNOWN",q instanceof g.wr&&"QUOTA_EXCEEDED"===q.type&&(t="OFFLINE_OPERATION_FAILURE_REASON_DATABASE_REQUEST_FAILED"),u.return(new D5("OFFLINE_ORCHESTRATION_ACTION_RESULT_FAILURE",c,void 0,t)));case 6:return u.return(new D5("OFFLINE_ORCHESTRATION_ACTION_RESULT_SUCCESS",c,m?[m]:void 0))}})},a1a=
function(a,b){var c,d;
return g.B(function(e){switch(e.j){case 1:return c=t5(b),g.wa(e,2),d=g.vC(b.entityKey).entityId,"!*$_ALL_ENTITIES_!*$"===d?g.A(e,B5(a.j,b,a.B),5):g.A(e,A5(d,a.j,b,a.B),5);case 5:g.ya(e,3);break;case 2:return g.za(e),e.return(new D5("OFFLINE_ORCHESTRATION_ACTION_RESULT_FAILURE",c,void 0,"OFFLINE_OPERATION_FAILURE_REASON_DATABASE_REQUEST_FAILED"));case 3:return e.return(new D5("OFFLINE_ORCHESTRATION_ACTION_RESULT_SUCCESS",c))}})},X0a=function(a,b,c,d){var e,f,h,l,m;
return g.B(function(n){switch(n.j){case 1:if(e=d){n.Oa(2);break}return g.A(n,a6([b]),3);case 3:f=n.u,e=f[0];case 2:return g.A(n,b1a(a,e,c),4);case 4:h=n.u;l=h.mainVideoEntity;m=h.channelEntity;var p=x5(l.thumbnail),q=x5(m.avatar);return g.A(n,s5(p.concat(q)),0)}})},b1a=function(a,b,c){var d,e,f,h,l;
return g.B(function(m){if(1==m.j){if(!(b&&b.channel&&b.channel.offlineChannelData&&b.videoId))throw Error("Invalid OfflineVideoData");c||(c=Date.now().toString());e=null==(d=b.channel)?void 0:d.offlineChannelData;f={id:g.wC(b.videoId,"ytMainChannelEntity"),channelId:e.channelId,title:e.title,avatar:e.thumbnail};h={key:g.wC(b.videoId,"mainVideoDownloadStateEntity"),playbackData:g.wC(b.videoId,"playbackData"),addedTimestampMillis:c};l={key:g.wC(b.videoId,"mainVideoEntity"),videoId:b.videoId,title:b.title,
thumbnail:b.thumbnail,localizedStrings:{viewCount:b.shortViewCountText},lengthSeconds:b.lengthSeconds?Number(b.lengthSeconds):void 0,publishedTimestampMillis:b.publishedTimestamp?(1E3*Number(b.publishedTimestamp)).toString():void 0,formattedDescription:b.description,owner:f.id,downloadState:h.key};return g.A(m,Z4(a.j,{mode:"readwrite",dc:!0},function(n){var p=T4(n,f,"ytMainChannelEntity"),q=T4(n,h,"mainVideoDownloadStateEntity");n=T4(n,l,"mainVideoEntity");return g.Dr.all([p,q,n])}),2)}return m.return({mainVideoEntity:l,
channelEntity:f})})},Y0a=function(a,b,c){b=g.wC(b,"playbackData");
c=Object.assign({},c,{priority:1,retryScheduleIntervalsInSeconds:c1a});return{actionType:a,entityKey:b,actionMetadata:c}},f6=function(a,b){this.j=a;
this.environmentData=b},e1a=function(a,b){var c,d,e,f,h,l,m,n,p,q,t,u,x,y;
return g.B(function(z){switch(z.j){case 1:c=t5(b);d=[];if(!a.environmentData.K("kevlar_smart_downloads")){z.Oa(2);break}g.wa(z,3);return g.A(z,N0a(),5);case 5:return e=z.u,g.A(z,d1a(e),6);case 6:var D;a:{var H;if(null!=(H=e.onResponseReceivedActions)&&H.length){var G;H=null==(D=e.onResponseReceivedActions[0].elementsCommand)?void 0:null==(G=D.offlineOrchestrationActionCommand)?void 0:G.actions;if(null!=H&&H.length){D=H;break a}}D=void 0}f=D;if(null==(h=f)?0:h.length)for(l=g.r(f),m=l.next();!m.done;m=
l.next())p=n=m.value,q=p.actionType,t=p.entityKey,u=p.actionMetadata,q&&t&&u&&!u.localImageEntityActionMetadata&&d.push(n);g.ya(z,2);break;case 3:return x=g.za(z),y="OFFLINE_OPERATION_FAILURE_REASON_UNKNOWN",x instanceof g.wr&&"QUOTA_EXCEEDED"===x.type&&(y="OFFLINE_OPERATION_FAILURE_REASON_DATABASE_REQUEST_FAILED"),z.return(new D5("OFFLINE_ORCHESTRATION_ACTION_RESULT_FAILURE",c,void 0,y));case 2:return z.return(new D5("OFFLINE_ORCHESTRATION_ACTION_RESULT_SUCCESS",c,d))}})},d1a=function(a){return g.B(function(b){return a.frameworkUpdates&&
a.frameworkUpdates.entityBatchUpdate?g.A(b,VZa(a.frameworkUpdates.entityBatchUpdate),0):b.return()})},g6=function(a,b,c){this.j=a;
this.environmentData=b;this.B=c},h1a=function(a,b){var c,d,e,f,h,l;
return g.B(function(m){switch(m.j){case 1:return c=t5(b),d=g.vC(b.entityKey),e=d.entityId,g.wa(m,2),g.A(m,f1a(a,e),4);case 4:g.ya(m,3);break;case 2:return f=g.za(m),h="OFFLINE_OPERATION_FAILURE_REASON_UNKNOWN",f instanceof g.wr&&"QUOTA_EXCEEDED"===f.type&&(h="OFFLINE_OPERATION_FAILURE_REASON_DATABASE_REQUEST_FAILED"),m.return(new D5("OFFLINE_ORCHESTRATION_ACTION_RESULT_FAILURE",c,void 0,h));case 3:var n;var p=null!=(n=b.actionMetadata)&&n.ytMainDownloadedVideoEntityActionMetadata?{playbackDataActionMetadata:{maximumDownloadQuality:b.actionMetadata.ytMainDownloadedVideoEntityActionMetadata.maximumDownloadQuality}}:
void 0;l=g1a("OFFLINE_ORCHESTRATION_ACTION_TYPE_ADD",e,p);return m.return(new D5("OFFLINE_ORCHESTRATION_ACTION_RESULT_SUCCESS",c,[l]))}})},i1a=function(a,b){var c,d,e,f,h,l,m;
return g.B(function(n){switch(n.j){case 1:return c=t5(b),d=g.vC(b.entityKey),e=d.entityId,g.A(n,b5(a.j,b.entityKey,"ytMainDownloadedVideoEntity"),2);case 2:f=n.u;if(!f)return n.return(new D5("OFFLINE_ORCHESTRATION_ACTION_RESULT_SUCCESS",c));g.wa(n,3);return g.A(n,f1a(a,e,f.addedTimestampMillis),5);case 5:h=g1a("OFFLINE_ORCHESTRATION_ACTION_TYPE_REFRESH",e);g.ya(n,4);break;case 3:return l=g.za(n),l instanceof Error&&"No data"===l.message?g.A(n,A5(e,a.j,b,a.B),4):(m="OFFLINE_OPERATION_FAILURE_REASON_UNKNOWN",
l instanceof g.wr&&"QUOTA_EXCEEDED"===l.type&&(m="OFFLINE_OPERATION_FAILURE_REASON_DATABASE_REQUEST_FAILED"),n.return(new D5("OFFLINE_ORCHESTRATION_ACTION_RESULT_FAILURE",c,void 0,m)));case 4:return n.return(new D5("OFFLINE_ORCHESTRATION_ACTION_RESULT_SUCCESS",c,h?[h]:void 0))}})},j1a=function(a,b){var c,d;
return g.B(function(e){switch(e.j){case 1:return c=t5(b),g.wa(e,2),d=g.vC(b.entityKey).entityId,"!*$_ALL_ENTITIES_!*$"===d?g.A(e,B5(a.j,b,a.B),5):g.A(e,A5(d,a.j,b,a.B),5);case 5:g.ya(e,3);break;case 2:return g.za(e),e.return(new D5("OFFLINE_ORCHESTRATION_ACTION_RESULT_FAILURE",c,void 0,"OFFLINE_OPERATION_FAILURE_REASON_DATABASE_REQUEST_FAILED"));case 3:return e.return(new D5("OFFLINE_ORCHESTRATION_ACTION_RESULT_SUCCESS",c))}})},f1a=function(a,b,c){var d,e,f,h,l;
return g.B(function(m){if(1==m.j)return g.A(m,a6([b]),2);if(3!=m.j)return d=m.u,e=d[0],g.A(m,k1a(a,e,c),3);f=m.u;h=f.videoEntity;l=f.channelEntity;var n=x5(h.thumbnail),p=x5(l.avatar);return g.A(m,s5(n.concat(p)),0)})},k1a=function(a,b,c){var d,e,f,h,l,m,n;
return g.B(function(p){if(1==p.j){if(!(b&&b.channel&&b.channel.offlineChannelData&&b.videoId))throw Error("Invalid OfflineVideoData");c||(c=Date.now().toString());e=null==(d=b.channel)?void 0:d.offlineChannelData;f={id:g.wC(b.videoId,"ytMainChannelEntity"),channelId:e.channelId,title:e.title,avatar:e.thumbnail};h={id:g.wC(b.videoId,"ytMainVideoEntity"),videoId:b.videoId,title:b.title,thumbnail:b.thumbnail,localizedStrings:{viewCount:b.shortViewCountText},lengthSeconds:b.lengthSeconds?Number(b.lengthSeconds):
void 0,publishedTimestampMillis:b.publishedTimestamp?(1E3*Number(b.publishedTimestamp)).toString():void 0,formattedDescription:b.description,channelOwner:f.id};l={id:g.wC(b.videoId,"ytMainDownloadedVideoEntity"),video:h.id,playbackData:g.wC(b.videoId,"playbackData"),offlineVideoPolicy:g.wC(b.videoId,"offlineVideoPolicy"),addedTimestampMillis:c};return a.environmentData.K("woffle_entity_migration")?(m={key:g.wC(b.videoId,"mainVideoDownloadStateEntity"),playbackData:g.wC(b.videoId,"playbackData"),addedTimestampMillis:c},
n={key:g.wC(b.videoId,"mainVideoEntity"),videoId:b.videoId,title:b.title,thumbnail:b.thumbnail,localizedStrings:{viewCount:b.shortViewCountText},lengthSeconds:b.lengthSeconds?Number(b.lengthSeconds):void 0,publishedTimestampMillis:b.publishedTimestamp?(1E3*Number(b.publishedTimestamp)).toString():void 0,formattedDescription:b.description,owner:f.id,downloadState:m.key},g.A(p,Z4(a.j,{mode:"readwrite",dc:!0},function(q){var t=T4(q,f,"ytMainChannelEntity"),u=T4(q,h,"ytMainVideoEntity"),x=T4(q,l,"ytMainDownloadedVideoEntity"),
y=T4(q,m,"mainVideoDownloadStateEntity");q=T4(q,n,"mainVideoEntity");return g.Dr.all([t,u,x,y,q])}),3)):g.A(p,Z4(a.j,{mode:"readwrite",
dc:!0},function(q){var t=T4(q,f,"ytMainChannelEntity"),u=T4(q,h,"ytMainVideoEntity");q=T4(q,l,"ytMainDownloadedVideoEntity");return g.Dr.all([t,u,q])}),3)}return p.return({videoEntity:h,
channelEntity:f,Tja:l})})},g1a=function(a,b,c){b=g.wC(b,"playbackData");
c=Object.assign({},c,{priority:1,retryScheduleIntervalsInSeconds:l1a});return{actionType:a,entityKey:b,actionMetadata:c}},h6=function(){Z5.apply(this,arguments);
this.I="ytMainDownloadedVideoEntity"},m1a=function(){var a;
return g.B(function(b){return 1==b.j?g.A(b,e5(),2):(a=b.u)?g.A(b,Z4(a,{mode:"readwrite",dc:!0},function(c){var d=R4(c,"ytMainDownloadedVideoEntity"),e=R4(c,"ytMainVideoEntity"),f=R4(c,"mainVideoEntity");return g.Dr.all([d,e,f]).then(function(h){h=g.r(h);var l=h.next().value,m=h.next().value,n=h.next().value;h={};l=g.r(l);for(var p=l.next();!p.done;p=l.next()){p=p.value;var q=g.vC(p.id).entityId;h[q]=p}l={};m=g.r(m);for(p=m.next();!p.done;p=m.next())p=p.value,q=g.vC(p.id).entityId,l[q]=p;m={};n=g.r(n);
for(p=n.next();!p.done;p=n.next())p=p.value,q=g.vC(p.key).entityId,m[q]=p;n=[];p=g.r(Object.keys(h));for(q=p.next();!q.done;q=p.next())if(q=q.value,!m[q]&&l[q]){var t=h[q],u=l[q];t={key:g.wC(q,"mainVideoDownloadStateEntity"),playbackData:g.wC(q,"playbackData"),addedTimestampMillis:t.addedTimestampMillis};q=[{key:g.wC(q,"mainVideoEntity"),videoId:q,title:u.title,thumbnail:u.thumbnail,localizedStrings:u.localizedStrings,lengthSeconds:u.lengthSeconds,publishedTimestampMillis:u.publishedTimestampMillis,
formattedDescription:u.formattedDescription,owner:u.channelOwner,downloadState:t.key},t];n.push(T4(c,q[0],"mainVideoEntity"),T4(c,q[1],"mainVideoDownloadStateEntity"))}return g.Dr.all(n)})}),0):b.return()})},i6=function(a,b){this.j=a;
this.B=b},p1a=function(a,b){var c,d,e,f,h,l;
return g.B(function(m){switch(m.j){case 1:return c=t5(b),d=g.vC(b.entityKey),e=d.entityId,g.wa(m,2),g.A(m,n1a(a,e),4);case 4:g.ya(m,3);break;case 2:return f=g.za(m),h="OFFLINE_OPERATION_FAILURE_REASON_UNKNOWN",f instanceof g.wr&&"QUOTA_EXCEEDED"===f.type&&(h="OFFLINE_OPERATION_FAILURE_REASON_DATABASE_REQUEST_FAILED"),m.return(new D5("OFFLINE_ORCHESTRATION_ACTION_RESULT_FAILURE",c,void 0,h));case 3:var n;var p=null!=(n=b.actionMetadata)&&n.musicTrackEntityActionMetadata?{playbackDataActionMetadata:{maximumDownloadQuality:b.actionMetadata.musicTrackEntityActionMetadata.maximumDownloadQuality}}:
void 0;l=o1a("OFFLINE_ORCHESTRATION_ACTION_TYPE_ADD",e,p);return m.return(new D5("OFFLINE_ORCHESTRATION_ACTION_RESULT_SUCCESS",c,[l]))}})},q1a=function(a,b){var c,d,e,f,h,l,m,n,p;
return g.B(function(q){switch(q.j){case 1:return c=t5(b),d=g.vC(b.entityKey),e=d.entityId,g.A(q,b5(a.j,b.entityKey,"musicTrack"),2);case 2:f=q.u;if(!f){h=void 0;q.Oa(3);break}return g.A(q,b5(a.j,f.downloadMetadata,"musicTrackDownloadMetadataEntity"),4);case 4:h=q.u;case 3:l=h;if(!f||!l)return q.return(new D5("OFFLINE_ORCHESTRATION_ACTION_RESULT_SUCCESS",c));g.wa(q,5);return g.A(q,n1a(a,e,l.addedTimestampMillis),7);case 7:m=o1a("OFFLINE_ORCHESTRATION_ACTION_TYPE_REFRESH",e);g.ya(q,6);break;case 5:return n=
g.za(q),n instanceof Error&&"No data"===n.message?g.A(q,z_a(e,a.j,b,a.B),6):(p="OFFLINE_OPERATION_FAILURE_REASON_UNKNOWN",n instanceof g.wr&&"QUOTA_EXCEEDED"===n.type&&(p="OFFLINE_OPERATION_FAILURE_REASON_DATABASE_REQUEST_FAILED"),q.return(new D5("OFFLINE_ORCHESTRATION_ACTION_RESULT_FAILURE",c,void 0,p)));case 6:return q.return(new D5("OFFLINE_ORCHESTRATION_ACTION_RESULT_SUCCESS",c,m?[m]:void 0))}})},r1a=function(a,b){var c,d;
return g.B(function(e){switch(e.j){case 1:return c=t5(b),g.wa(e,2),d=g.vC(b.entityKey).entityId,"!*$_ALL_ENTITIES_!*$"===d?g.A(e,A_a(a.j,b,a.B),5):g.A(e,z_a(d,a.j,b,a.B),5);case 5:g.ya(e,3);break;case 2:return g.za(e),e.return(new D5("OFFLINE_ORCHESTRATION_ACTION_RESULT_FAILURE",c,void 0,"OFFLINE_OPERATION_FAILURE_REASON_DATABASE_REQUEST_FAILED"));case 3:return e.return(new D5("OFFLINE_ORCHESTRATION_ACTION_RESULT_SUCCESS",c))}})},n1a=function(a,b,c){var d,e,f,h,l;
return g.B(function(m){if(1==m.j)return g.A(m,a6([b]),2);if(3!=m.j)return d=m.u,e=d[0],g.A(m,s1a(a,e,c),3);f=m.u;h=f.musicTrackEntity;l=f.musicArtistEntity;var n=x5(h.thumbnailDetails),p=x5(l.thumbnailDetails);return g.A(m,s5(n.concat(p)),0)})},s1a=function(a,b,c){var d,e,f,h,l,m,n,p,q,t,u,x,y,z;
return g.B(function(D){if(1==D.j){if(!(b&&b.channel&&b.channel.offlineChannelData&&b.videoId&&b.additionalMetadatas))throw Error("Invalid OfflineVideoData");c||(c=Date.now().toString());e=g.r(b.additionalMetadatas);for(f=e.next();!f.done;f=e.next())h=f.value,h.offlineMusicVideoData&&(d=h.offlineMusicVideoData);if(!d)throw Error("Invalid OfflineMusicVideoData");m=null==(l=b.channel)?void 0:l.offlineChannelData;n={id:g.wC(b.videoId,"musicArtist"),externalChannelId:m.channelId,name:m.title,thumbnailDetails:m.thumbnail};
p={id:g.wC(b.videoId,"musicTrackDownloadMetadataEntity"),playbackData:g.wC(b.videoId,"playbackData"),addedTimestampMillis:c};z={id:g.wC(b.videoId,"musicTrack"),videoId:b.videoId,title:b.title,thumbnailDetails:b.thumbnail,lengthMs:String(1E3*Number(b.lengthSeconds)),albumTitle:null==(q=d)?void 0:q.releaseTitle,musicVideoType:null==(t=d)?void 0:t.musicVideoType,contentRating:{explicitType:null==(u=d)?void 0:u.explicitType},artists:[n.id],artistNames:(null==(x=d)?void 0:x.byline)||(null==(y=d)?void 0:
y.channelName),downloadMetadata:p.id};return g.A(D,Z4(a.j,{mode:"readwrite",dc:!0},function(H){var G=T4(H,n,"musicArtist"),L=T4(H,p,"musicTrackDownloadMetadataEntity");H=T4(H,z,"musicTrack");return g.Dr.all([G,L,H])}),2)}return D.return({musicTrackEntity:z,
musicArtistEntity:n})})},o1a=function(a,b,c){b=g.wC(b,"playbackData");
c=Object.assign({},c,{priority:1,retryScheduleIntervalsInSeconds:t1a});return{actionType:a,entityKey:b,actionMetadata:c}},j6=function(){Z5.apply(this,arguments);
this.I="musicTrack"},k6=function(){g.PI.apply(this,arguments)};
g.w(J3,I3);g.ha.Object.defineProperties(J3.prototype,{entityMetadata:{configurable:!0,enumerable:!0,get:function(){return this.j.entityMetadata},
set:function(a){this.j.entityMetadata=a}}});
g.w(K3,J3);K3.prototype.u=function(){return[]};
g.w(L3,J3);L3.prototype.u=function(){var a=[];this.j.alternateChannel&&a.push(this.j.alternateChannel);this.j.alternateChannelList&&a.push.apply(a,g.v(this.j.alternateChannelList));this.j.oneofChannelEntity&&a.push(this.j.oneofChannelEntity);return[].concat(g.v(new Set(a)))};
g.w(M3,J3);M3.prototype.u=function(){var a=[];this.j.entryCollection&&a.push(this.j.entryCollection);return[].concat(g.v(new Set(a)))};
g.w(N3,I3);N3.prototype.u=function(){var a=[];this.j.video&&a.push(this.j.video);return[].concat(g.v(new Set(a)))};
g.w(O3,J3);O3.prototype.u=function(){var a=[];this.j.parentPlaylist&&a.push(this.j.parentPlaylist);if(this.j.entries)for(var b=g.r(this.j.entries),c=b.next();!c.done;c=b.next())a.push.apply(a,g.v((new N3(c.value)).u()));return[].concat(g.v(new Set(a)))};
g.w(P3,J3);P3.prototype.u=function(){var a=[];this.j.descriptionEntity&&a.push(this.j.descriptionEntity);this.j.creators&&a.push.apply(a,g.v(this.j.creators));this.j.theBiggestFan&&a.push(this.j.theBiggestFan);return[].concat(g.v(new Set(a)))};
g.w(Q3,J3);Q3.prototype.u=function(){return[]};
g.w(R3,J3);R3.prototype.u=function(){return[]};
g.w(S3,J3);S3.prototype.u=function(){return[]};
g.w(T3,J3);T3.prototype.u=function(){return[]};
g.w(U3,J3);U3.prototype.u=function(){return[]};
g.w(V3,I3);V3.prototype.u=function(){var a=[];this.j.video&&a.push(this.j.video);this.j.playlist&&a.push(this.j.playlist);this.j.videoItem&&a.push(this.j.videoItem);return[].concat(g.v(new Set(a)))};
g.w(W3,J3);W3.prototype.u=function(){var a=[];this.j.refresh&&a.push(this.j.refresh);if(this.j.downloads)for(var b=g.r(this.j.downloads),c=b.next();!c.done;c=b.next())a.push.apply(a,g.v((new V3(c.value)).u()));return[].concat(g.v(new Set(a)))};
g.w(X3,J3);X3.prototype.u=function(){var a=[];this.j.playbackData&&a.push(this.j.playbackData);this.j.localImageEntities&&a.push.apply(a,g.v(this.j.localImageEntities));return[].concat(g.v(new Set(a)))};
g.w(Y3,J3);Y3.prototype.u=function(){return[]};
g.w(Z3,J3);Z3.prototype.u=function(){var a=[];this.j.fakeChildren&&a.push.apply(a,g.v(this.j.fakeChildren));return[].concat(g.v(new Set(a)))};
g.w($3,J3);$3.prototype.u=function(){var a=[];this.j.video&&a.push(this.j.video);this.j.playbackData&&a.push(this.j.playbackData);this.j.offlineVideoPolicy&&a.push(this.j.offlineVideoPolicy);return[].concat(g.v(new Set(a)))};
g.w(a4,J3);a4.prototype.u=function(){var a=[];this.j.channelOwner&&a.push(this.j.channelOwner);this.j.videos&&a.push.apply(a,g.v(this.j.videos));this.j.collaboratorChannels&&a.push.apply(a,g.v(this.j.collaboratorChannels));return[].concat(g.v(new Set(a)))};
g.w(b4,J3);b4.prototype.u=function(){var a=[];this.j.video&&a.push(this.j.video);this.j.channelContributor&&a.push(this.j.channelContributor);return[].concat(g.v(new Set(a)))};
g.w(c4,I3);c4.prototype.u=function(){var a=[];this.j.playbackPosition&&a.push(this.j.playbackPosition);return[].concat(g.v(new Set(a)))};
g.w(d4,J3);d4.prototype.u=function(){var a=[];this.j.owner&&a.push(this.j.owner);this.j.downloadState&&a.push(this.j.downloadState);this.j.userState&&a.push.apply(a,g.v((new c4(this.j.userState)).u()));return[].concat(g.v(new Set(a)))};
g.w(e4,J3);e4.prototype.u=function(){return[]};
g.w(f4,J3);f4.prototype.u=function(){var a=[];this.j.channelOwner&&a.push(this.j.channelOwner);this.j.playbackPosition&&a.push(this.j.playbackPosition);this.j.localImageEntities&&a.push.apply(a,g.v(this.j.localImageEntities));this.j.downloadStatus&&a.push(this.j.downloadStatus);return[].concat(g.v(new Set(a)))};
g.w(g4,J3);g4.prototype.u=function(){return[]};
g.w(h4,J3);h4.prototype.u=function(){return[]};
g.w(i4,J3);i4.prototype.u=function(){return[]};
g.w(j4,J3);j4.prototype.u=function(){var a=[];this.j.trackDownloadMetadatas&&a.push.apply(a,g.v(this.j.trackDownloadMetadatas));return[].concat(g.v(new Set(a)))};
g.w(k4,J3);k4.prototype.u=function(){var a=[];this.j.playbackData&&a.push(this.j.playbackData);this.j.localImageEntities&&a.push.apply(a,g.v(this.j.localImageEntities));return[].concat(g.v(new Set(a)))};
g.w(l4,J3);l4.prototype.u=function(){var a=[];this.j.musicLibraryStatusEntity&&a.push(this.j.musicLibraryStatusEntity);this.j.primaryArtists&&a.push.apply(a,g.v(this.j.primaryArtists));this.j.details&&a.push(this.j.details);this.j.userDetails&&a.push(this.j.userDetails);this.j.tracks&&a.push.apply(a,g.v(this.j.tracks));this.j.share&&a.push(this.j.share);this.j.downloadMetadata&&a.push(this.j.downloadMetadata);return[].concat(g.v(new Set(a)))};
g.w(m4,J3);m4.prototype.u=function(){var a=[];this.j.albumRelease&&a.push(this.j.albumRelease);this.j.tracks&&a.push.apply(a,g.v(this.j.tracks));return[].concat(g.v(new Set(a)))};
g.w(n4,J3);n4.prototype.u=function(){var a=[];this.j.albumRelease&&a.push(this.j.albumRelease);return[].concat(g.v(new Set(a)))};
g.w(o4,J3);o4.prototype.u=function(){var a=[];this.j.details&&a.push(this.j.details);this.j.userDetails&&a.push(this.j.userDetails);return[].concat(g.v(new Set(a)))};
g.w(p4,J3);p4.prototype.u=function(){var a=[];this.j.parentArtist&&a.push(this.j.parentArtist);return[].concat(g.v(new Set(a)))};
g.w(q4,J3);q4.prototype.u=function(){var a=[];this.j.parentArtist&&a.push(this.j.parentArtist);return[].concat(g.v(new Set(a)))};
g.w(r4,J3);r4.prototype.u=function(){return[]};
g.w(s4,J3);s4.prototype.u=function(){return[]};
g.w(t4,J3);t4.prototype.u=function(){return[]};
g.w(u4,J3);
u4.prototype.u=function(){var a=[];this.j.musicLibraryStatusEntity&&a.push(this.j.musicLibraryStatusEntity);this.j.artists&&a.push.apply(a,g.v(this.j.artists));this.j.audioModeVersion&&a.push(this.j.audioModeVersion);this.j.videoModeVersion&&a.push(this.j.videoModeVersion);this.j.userDetails&&a.push(this.j.userDetails);this.j.details&&a.push(this.j.details);this.j.albumRelease&&a.push(this.j.albumRelease);this.j.share&&a.push(this.j.share);this.j.libraryEdit&&a.push(this.j.libraryEdit);this.j.downloadMetadata&&
a.push(this.j.downloadMetadata);return[].concat(g.v(new Set(a)))};
g.w(v4,J3);v4.prototype.u=function(){var a=[];this.j.parentTrack&&a.push(this.j.parentTrack);return[].concat(g.v(new Set(a)))};
g.w(w4,J3);w4.prototype.u=function(){var a=[];this.j.parentTrack&&a.push(this.j.parentTrack);return[].concat(g.v(new Set(a)))};
g.w(x4,J3);x4.prototype.u=function(){return[]};
g.w(y4,J3);y4.prototype.u=function(){return[]};
g.w(z4,J3);z4.prototype.u=function(){return[]};
g.w(A4,J3);A4.prototype.u=function(){return[]};
g.w(B4,J3);B4.prototype.u=function(){var a=[];this.j.transfer&&a.push(this.j.transfer);this.j.adsPlaybackData&&a.push.apply(a,g.v(this.j.adsPlaybackData));this.j.drmLicense&&a.push(this.j.drmLicense);this.j.offlineVideoPolicy&&a.push(this.j.offlineVideoPolicy);return[].concat(g.v(new Set(a)))};
g.w(C4,J3);C4.prototype.u=function(){return[]};
g.w(D4,J3);D4.prototype.u=function(){var a=[];this.j.offlineVideoStreams&&a.push.apply(a,g.v(this.j.offlineVideoStreams));this.j.captionTrack&&a.push.apply(a,g.v(this.j.captionTrack));return[].concat(g.v(new Set(a)))};
g.w(E4,J3);E4.prototype.u=function(){return[]};
g.w(F4,J3);F4.prototype.u=function(){return[]};
g.w(G4,J3);G4.prototype.u=function(){return[]};
g.w(H4,J3);H4.prototype.u=function(){return[]};
g.w(I4,J3);I4.prototype.u=function(){return[]};
var M0a=["browse","music/browse","unplugged/browse"],K0a=["offline"],G_a=["offline/get_playback_data_entity"],K4;g.w(L4,g.rr);g.w(N4,EZa);N4.prototype.B=function(a,b){b=M4(b);a=(new TextEncoder).encode(JSON.stringify(a));return this.j.encrypt(a,b)};
N4.prototype.u=function(a,b){if(!(a instanceof Uint8Array))throw AZa(1);var c=new TextDecoder;b=M4(b);a=this.j.decrypt(a,b);return JSON.parse(c.decode(a))};
var GZa={buttonEntity:E4,captionTrack:x4,channelHandle:K3,commerceCartListEntity:G4,downloadQualityPickerEntity:T3,downloadsPageRefreshTokenEntity:U3,downloadsPageViewConfigurationEntity:g4,fakeChannel:L3,fakePlaylist:M3,fakePlaylistEntryCollection:O3,fakeVideo:P3,fakeVideoDescription:Q3,iconBadgeEntity:H4,liveChatPollStateEntity:S3,logoEntity:R3,mainDownloadsListEntity:W3,mainPlaylistEntity:a4,mainPlaylistVideoEntity:b4,mainVideoDownloadStateEntity:X3,mainVideoEntity:d4,markersVisibilityOverrideEntity:h4,
musicAlbumReleaseDetail:m4,musicAlbumReleaseDownloadMetadataEntity:j4,musicAlbumRelease:l4,musicAlbumReleaseUserDetail:n4,musicArtistDetail:p4,musicArtist:o4,musicArtistUserDetail:q4,musicLibraryEdit:r4,musicLibraryStatusEntity:s4,musicShare:t4,musicTrackDetail:v4,musicTrackDownloadMetadataEntity:k4,musicTrack:u4,musicTrackUserDetail:w4,offlineOrchestrationActionWrapperEntity:y4,offlineVideoPolicy:z4,offlineVideoStreams:A4,offlineabilityEntity:Y3,orchestrationWebSamplingEntity:Z3,pinnedProductEntity:i4,
playbackData:B4,quantityIncrementerEntity:I4,refresh:C4,transfer:D4,videoPlaybackPositionEntity:F4,ytMainChannelEntity:e4,ytMainDownloadedVideoEntity:$3,ytMainVideoEntity:f4};IZa.prototype.updateEntity=function(a,b,c,d){var e=this,f=O4(this.u,1);return Q4(this,a,c).then(function(h){if(h){h=g.fC(h,b,d);var l={key:a,entityType:c,data:FZa(f,h,a),version:1};return g.Dr.all([g.Mr(e.j.objectStore("EntityStore"),l),JZa(e,h,c)])}}).then(function(){S4(e,a,c);
return a})};
g.w(X4,EZa);X4.prototype.B=function(a){return a};
X4.prototype.u=function(a){if(a instanceof Uint8Array)throw AZa(0);return a};
g.w(Y4,g.I);Y4.prototype.u=function(a){PZa(this,a.data)};
Y4.prototype.Y=function(){this.channel.close()};
var d5,u1a={K3:"captionTrack",v7:"ytMainDownloadedVideoEntity",w7:"ytMainVideoEntity",paa:"ytMainChannelEntity",qaa:"mainPlaylistEntity",raa:"mainPlaylistVideoEntity",saa:"mainVideoEntity",taa:"mainVideoDownloadStateEntity",Aca:"musicAlbumReleaseDetail",Bca:"musicAlbumReleaseDownloadMetadataEntity",Cca:"musicAlbumRelease",Dca:"musicAlbumReleaseUserDetail",Eca:"musicArtistDetail",Fca:"musicArtist",Hca:"musicArtistUserDetail",Qca:"musicLibraryEdit",Rca:"musicLibraryStatusEntity",cda:"musicShare",hda:"musicTrackDetail",
ida:"musicTrackDownloadMetadataEntity",jda:"musicTrack",kda:"musicTrackUserDetail",Ada:"offlineOrchestrationActionWrapperEntity",Kda:"offlineVideoPolicy",Lda:"offlineVideoStreams",xea:"playbackData",Afa:"orchestrationWebSamplingEntity",Iga:"downloadsPageViewConfigurationEntity",Jga:"refresh",Kga:"mainDownloadsListEntity",Lga:"downloadsPageRefreshTokenEntity",tha:"transfer"};g.w(g5,g.I);g5.prototype.B=function(a){this.api.Ia("onOfflineOperationFailure",a.data)};
g5.prototype.C=function(a){this.api.W("offlinetransferpause",a.data)};
g5.prototype.Y=function(){var a;null==(a=this.j)||a.close();var b;null==(b=this.u)||b.close()};g_a.prototype.request=function(a,b,c){b=void 0===b?{}:b;return this.locks.request(a,b,function(d){return c(d)})};j_a.prototype.nf=function(){this.j&&i5(this)};var o5=g.C.caches,n5,p5;k5.prototype.open=function(a){return o5.open(m5(a))};
k5.prototype.has=function(a){return o5.has(m5(a))};
k5.prototype.delete=function(a){return o5.delete(m5(a))};
k5.prototype.match=function(a,b){var c=this,d,e,f,h,l,m;return g.B(function(n){switch(n.j){case 1:return g.A(n,c.keys(),2);case 2:d=n.u,e=g.r(d),f=e.next();case 3:if(f.done){n.Oa(5);break}h=f.value;return g.A(n,c.open(h),6);case 6:return l=n.u,g.A(n,l.match(a,b),7);case 7:if(m=n.u)return n.return(m);f=e.next();n.Oa(3);break;case 5:return n.return()}})};
g.w(l5,k5);l5.prototype.keys=function(){var a,b,c,d,e,f,h,l,m;return g.B(function(n){if(1==n.j)return a=[],b=g.sr("CacheStorage keys"),g.A(n,o5.keys(),2);c=n.u;d=g.r(c);for(e=d.next();!e.done;e=d.next()){f=e.value;var p=f.indexOf(":");h=-1===p?{BC:f}:{BC:f.substring(0,p),datasyncId:f.substring(p+1)};l=h.BC;m=h.datasyncId;m===b&&a.push(l)}return n.return(a)})};Object.keys(u1a).map(function(a){return u1a[a]});
var x_a="captionTrack ytMainDownloadedVideoEntity ytMainVideoEntity ytMainChannelEntity mainPlaylistEntity mainVideoEntity mainVideoDownloadStateEntity musicArtist musicTrack musicTrackDownloadMetadataEntity offlineVideoPolicy offlineVideoStreams playbackData transfer".split(" ");g.w(E5,C5);E5.prototype.u=function(a){return u5(a)?E_a(this,a):v5(a)?F_a(this,a):Promise.reject(Error("Unsupported action type: "+a.actionType))};g.w(G5,C5);G5.prototype.u=function(a){return u5(a)?I_a(this,a):v5(a)?J_a(this,a):"OFFLINE_ORCHESTRATION_ACTION_TYPE_UPDATE"===a.actionType&&a.entityKey?this.handleUpdate(a):Promise.reject(Error("Unsupported action type: "+a.actionType))};
G5.prototype.handleUpdate=function(a){var b=this,c,d,e;return g.B(function(f){switch(f.j){case 1:return c=t5(a),g.A(f,b5(b.j,a.entityKey,"transfer"),2);case 2:d=f.u;if(!d||"TRANSFER_STATE_WAITING_FOR_PLAYER_RESPONSE_REFRESH"!==d.transferState)return f.return(new D5("OFFLINE_ORCHESTRATION_ACTION_RESULT_SUCCESS",c));g.wa(f,3);d.transferState="TRANSFER_STATE_TRANSFER_IN_QUEUE";return g.A(f,a5(b.j,d,"transfer"),5);case 5:e=g.vC(d.key).entityId;j5({transferStatusType:"TRANSFER_STATUS_TYPE_REENQUEUED_BY_PLAYER_RESPONSE_REFRESH",
statusType:"ADDED_TO_QUEUE"},{videoId:e,nj:d});g.ya(f,4);break;case 3:return g.za(f),f.return(new D5("OFFLINE_ORCHESTRATION_ACTION_RESULT_FAILURE",c,void 0,"OFFLINE_OPERATION_FAILURE_REASON_DATABASE_REQUEST_FAILED"));case 4:return f.return(new D5("OFFLINE_ORCHESTRATION_ACTION_RESULT_SUCCESS",c))}})};var Z_a=["OFFLINE_ORCHESTRATION_ACTION_TYPE_ADD","OFFLINE_ORCHESTRATION_ACTION_TYPE_REFRESH"];var J5;R_a.prototype.j=function(a,b){var c=a.action.actionMetadata.priority-b.action.actionMetadata.priority;0===c&&(a.j<b.j?c=-1:a.j>b.j&&(c=1));return c};g.w(M5,g.I);M5.prototype.Y=function(){this.J&&this.J();g.I.prototype.Y.call(this)};
M5.prototype.createAction=function(a,b){var c=g.vC(a.entityKey).entityType,d=g.Cu(16);return new H5(c,d,a,b.actionId,b.rootActionId)};
M5.prototype.V=function(a){var b=this,c,d,e,f,h,l,m,n,p;return g.B(function(q){if(1==q.j){if(b.isDisposed())return q.return();d=null!=(c=a.offlineOrchestrationActionWrapperEntity)?c:new Set;e=[];f=g.r(d);for(h=f.next();!h.done;h=f.next())l=h.value,m=g.vC(l),n=m.entityId,T_a(b.j,n)||e.push(l);return g.A(q,a0a(b,e),2)}p=q.u;return g.A(q,O5(b,p),0)})};
M5.prototype.retry=function(){var a=this;return g.B(function(b){return g.A(b,b0a(a),0)})};g.k=h0a.prototype;g.k.UY=function(a){var b=this,c,d,e;return g.B(function(f){if(!g.V(a.state,128))return f.Oa(0);var h=null==(c=a.state.getData())?void 0:c.errorCode;a.state.getData();var l=null==(d=a.state.getData())?void 0:d.cB;e="net.connect"===h&&1===l?"TRANSFER_FAILURE_REASON_NETWORK_LOST":(null==h?0:h.startsWith("net."))?"TRANSFER_FAILURE_REASON_NETWORK":"TRANSFER_FAILURE_REASON_INTERNAL";return g.A(f,b.Xr(b.player.getVideoData().videoId,e),0)})};
g.k.Xr=function(a,b){var c=this;return g.B(function(d){if(1==d.j){if(c.u)return d.return();c.u=!0;return"TRANSFER_FAILURE_REASON_NETWORK_LOST"===b?(Q5(c,a,!1,!0),d.Oa(0)):g.A(d,P5(c,a),3)}g.IC(a,4);return g.A(d,c.j.Xr(b),0)})};
g.k.tC=function(a){2===a.status?(a.status!==this.B&&(V5(this.j),g.IC(a.videoId,2)),a.ez&&C0a(this.j,a.videoId,a.ez)):4===a.status?(P5(this,a.videoId),this.Xr(a.videoId,a.JB?"TRANSFER_FAILURE_REASON_FILESYSTEM_WRITE":"TRANSFER_FAILURE_REASON_INTERNAL")):1===a.status&&A0a(this.j);this.B=a.status;this.api.Ia("localmediachange",{videoId:a.videoId,status:a.status})};
g.k.gI=function(){var a=this,b;return g.B(function(c){if(1==c.j){if(a.u)return c.return();a.u=!0;b=a.player.getVideoData().videoId;return g.A(c,P5(a,b),2)}return g.A(c,a.j.gI(),0)})};
g.k.K=function(a){return this.api.S().K(a)};g.w(R5,g.I);R5.prototype.Y=function(){this.u&&this.u();g.I.prototype.Y.call(this)};
R5.prototype.B=function(a){var b=this,c,d,e,f,h,l,m,n;return g.B(function(p){d=null!=(c=a.transfer)?c:new Set;e=[];f=g.r(d);for(h=f.next();!h.done;h=f.next())l=h.value,m=g.vC(l),n=m.entityId,e.push(n);return 0===e.length?p.return():g.A(p,o0a(b,e),0)})};g.w(S5,g.I);g.k=S5.prototype;g.k.Y=function(){this.J&&this.J();this.P.dispose();this.C.dispose();this.Z&&g.Ue(this.D.B,this.Z);this.V&&g.Ue(this.D.B,this.V);g.I.prototype.Y.call(this)};
g.k.f0=function(a){var b=this,c,d;return g.B(function(e){if(1==e.j)return c=g.wC(a,"transfer"),b.j&&c===b.j.key?(Q5(b.I,b.B,!0),b.C.stop(),e.Oa(0)):g.A(e,Z4(b.u,{mode:"readwrite",dc:!0},function(f){return Q4(f,c,"transfer").then(function(h){if(h&&"TRANSFER_STATE_COMPLETE"!==h.transferState&&"TRANSFER_STATE_FAILED"!==h.transferState)return h.transferState="TRANSFER_STATE_PAUSED_BY_USER",T4(f,h,"transfer").then(function(){return h})})}),3);
(d=e.u)&&p_a({videoId:a,nj:d});g.va(e)})};
g.k.e0=function(){this.j&&this.B&&Q5(this.I,this.B,!1);this.C.stop()};
g.k.pz=function(){this.j?u0a(this,this.j):U5(this)};
g.k.NS=function(a){var b=this,c;return g.B(function(d){switch(d.j){case 1:if(!b.j){d.Oa(2);break}if("TRANSFER_STATE_COMPLETE"===b.j.transferState||"TRANSFER_STATE_FAILED"===b.j.transferState||!a.transfer||!a.transfer.has(b.j.key)){d.Oa(3);break}c=b;return g.A(d,b5(b.u,b.j.key,"transfer"),4);case 4:c.j=d.u;if(b.j){d.Oa(3);break}return g.A(d,v0a(b),3);case 3:if(b.j)return d.return();case 2:return g.A(d,U5(b),0)}})};
g.k.Xr=function(a,b){var c=this,d,e;return g.B(function(f){if(1==f.j){a:switch(a){case "TRANSFER_FAILURE_REASON_FILESYSTEM_WRITE":case "TRANSFER_FAILURE_REASON_EXTERNAL_FILESYSTEM_WRITE":case "TRANSFER_FAILURE_REASON_PLAYABILITY":case "TRANSFER_FAILURE_REASON_TOO_MANY_RETRIES":var h=!1;break a;default:h=!0}return h&&D0a(c)?g.A(f,X5(c,"TRANSFER_STATE_TRANSFER_IN_QUEUE"),5):g.A(f,E0a(c,a),3)}3!=f.j&&(d=g.vC(c.j.key).entityId,j5({transferStatusType:"TRANSFER_STATUS_TYPE_REENQUEUED_BY_RETRY",statusType:"ADDED_TO_QUEUE"},
{videoId:d,nj:c.j}));T5(c);e=U5(c,!0);b&&b(e);g.va(f)})};
g.k.gI=function(a){var b=this,c,d,e,f,h,l;return g.B(function(m){if(1==m.j)return D0a(b)?g.A(m,X5(b,"TRANSFER_STATE_WAITING_FOR_PLAYER_RESPONSE_REFRESH"),5):g.A(m,E0a(b,"TRANSFER_FAILURE_REASON_STREAM_MISSING"),3);if(3!=m.j)return c=g.vC(b.j.key).entityId,j5({transferStatusType:"TRANSFER_STATUS_TYPE_DEQUEUED_BY_PLAYER_RESPONSE_EXPIRATION",statusType:"ADDED_TO_QUEUE"},{videoId:c,nj:b.j}),d=L_a(),d.playbackDataActionMetadata={isEnqueuedForExpiredStreamUrlRefetch:!0},e=g.wC(c,"playbackData"),f={actionType:"OFFLINE_ORCHESTRATION_ACTION_TYPE_ADD",
entityKey:e,actionMetadata:d},h=I5(new H5("playbackData",c,f)),g.A(m,a5(b.u,h,"offlineOrchestrationActionWrapperEntity"),3);T5(b);l=U5(b,!0);a&&a(l);g.va(m)})};
var l6={},Y5=(l6.TRANSFER_STATE_TRANSFERRING=1,l6.TRANSFER_STATE_TRANSFER_IN_QUEUE=2,l6);g.k=Z5.prototype;g.k.Kx=function(a){var b={};return b.playbackData=new E5(a,this.environmentData,this.u),b.transfer=new G5(a),b};
g.k.YI=function(){var a=this;return g.B(function(b){return a.j?g.A(b,s0a(a.j),0):b.Oa(0)})};
g.k.isOrchestrationLeader=function(){return this.B.j};
g.k.wI=function(a){var b=this.u;b.api.W("offlinetransferpause",a);var c;null==(c=b.u)||c.postMessage(a)};
g.k.pz=function(a){var b,c;return g.B(function(d){if(1==d.j)return g.A(d,e5(),2);b=d.u;if(!b)return d.return();c=g.wC(a,"transfer");return g.A(d,Z4(b,{mode:"readwrite",dc:!0},function(e){return Q4(e,c,"transfer").then(function(f){return f&&"TRANSFER_STATE_PAUSED_BY_USER"===f.transferState?(f.transferState="TRANSFER_STATE_TRANSFER_IN_QUEUE",T4(e,f,"transfer").then(function(){j5({transferStatusType:"TRANSFER_STATUS_TYPE_REENQUEUED_BY_USER_RESUME",statusType:"USER_RESUMED"},{videoId:a,nj:f});return g.Dr.resolve(null)})):
g.Dr.resolve(null)})}),0)})};
g.k.mz=function(a){a=void 0===a?43200:a;var b=this,c,d,e,f,h,l,m,n;return g.B(function(p){if(1==p.j)return b.P.mf()?g.A(p,e5(),2):p.return(J0a());if(3!=p.j){c=p.u;if(!c)return p.return([]);d=Date.now()/1E3;return g.A(p,c5(c,"offlineVideoPolicy"),3)}e=p.u;f=[];h=g.r(e);for(l=h.next();!l.done;l=h.next())m=l.value,Number(m.lastUpdatedTimestampSeconds)+a<=d&&(n=g.vC(m.key).entityId,f.push(n));return f.length?p.return($5(b,f,b.I,"OFFLINE_ORCHESTRATION_ACTION_TYPE_REFRESH")):p.return([])})};
g.k.deleteAll=function(){return $5(this,["!*$_ALL_ENTITIES_!*$"],this.I,"OFFLINE_ORCHESTRATION_ACTION_TYPE_DELETE")};g.w(b6,C5);b6.prototype.u=function(a){return u5(a)?P0a(this,a):v5(a)?Q0a(this,a):w5(a)?R0a(this,a):Promise.reject(Error("Unsupported action type: "+a.actionType))};
var W0a=[10];g.w(e6,C5);e6.prototype.u=function(a){return u5(a)?Z0a(this,a):v5(a)?$0a(this,a):w5(a)?a1a(this,a):Promise.reject(Error("Unsupported action type: "+a.actionType))};
var c1a=[10];g.w(f6,C5);f6.prototype.u=function(a){return v5(a)?e1a(this,a):Promise.reject(Error("Unsupported action type: "+a.actionType))};g.w(g6,C5);g6.prototype.u=function(a){return u5(a)?h1a(this,a):v5(a)?i1a(this,a):w5(a)?j1a(this,a):Promise.reject(Error("Unsupported action type: "+a.actionType))};
var l1a=[10];g.w(h6,Z5);h6.prototype.Kx=function(a){var b=Z5.prototype.Kx.call(this,a);b.ytMainDownloadedVideoEntity=new g6(a,this.environmentData,this.u);b.mainVideoEntity=new e6(a,this.u);b.mainPlaylistEntity=new b6(a,this.u);b.mainDownloadsListEntity=new f6(a,this.environmentData);return b};
h6.prototype.YI=function(){var a=this;return g.B(function(b){return 1==b.j?g.A(b,Z5.prototype.YI.call(a),2):a.environmentData.K("woffle_entity_migration")?g.A(b,m1a(),0):b.Oa(0)})};g.w(i6,C5);i6.prototype.u=function(a){return u5(a)?p1a(this,a):v5(a)?q1a(this,a):w5(a)?r1a(this,a):Promise.reject(Error("Unsupported action type: "+a.actionType))};
var t1a=[10];g.w(j6,Z5);j6.prototype.Kx=function(a){var b=Z5.prototype.Kx.call(this,a);b.musicTrack=new i6(a,this.u);return b};g.w(k6,g.PI);g.k=k6.prototype;g.k.create=function(){var a=this.player.S();g.qB(a)?this.j=new h6(a,this.player):g.aB(a)&&(this.j=new j6(a,this.player))};
g.k.ij=function(){return!1};
g.k.JI=function(a,b,c,d){var e=this;return g.B(function(f){return e.j?f.return($5(e.j,a,b,c,d)):f.return(Promise.reject())})};
g.k.deleteAll=function(){return this.j.deleteAll()};
g.k.mz=function(a){return this.j.mz(a)};
g.k.wI=function(a){this.j.wI(a)};
g.k.pz=function(a){return this.j.pz(a)};
g.k.isOrchestrationLeader=function(){return this.j.isOrchestrationLeader()};g.OI("offline",k6);})(_yt_player);
